### ISSUE TITLE
New dropdown UI enhancement.

### ISSUE THREAD

**Issue by Ashish1998** [chimple/cuba#1002]
In the new drop down UI the options in the drop down looks very close to each other and in mobile devices we feel it might be difficult to click on the option. 

**Screenshots**
![Screenshot_2023-10-30-11-00-45-64_ddc0fec0f25cadbb53407d57e5100bc9](https://github.com/chimple/cuba/assets/99384703/c8a6eb33-ef8c-4bd9-9ce6-0ecf673e8d66)
![Screenshot_2023-10-30-11-02-13-73_ddc0fec0f25cadbb53407d57e5100bc9](https://github.com/chimple/cuba/assets/99384703/da17a8f4-28ca-456e-9e9c-be67c5ecb460)

**Comment by pratapramesh** [comment]
**1. while selecting 'Grade' and 'medium of instruction'  if i go to sleep and come back, the drop-down is not displaying**
![Screenshot_2023-11-03-12-05-16-605](https://github.com/chimple/cuba/assets/138564361/3c26a7e7-3503-4557-80e8-57b3c08922d6)


**2. Place holder is missing in the dropdown**

![Screenshot_2023-11-06-12-03-52-836](https://github.com/chimple/cuba/assets/138564361/e2cfebdb-4df5-4549-8089-64c43f03d58c)

**For Example:**
![Screenshot_2023-11-06-11-51-59-988](https://github.com/chimple/cuba/assets/138564361/19be2d89-2881-4b87-a180-79e7a47cd751)

**Comment by pratapramesh** [comment]
**1. While selecting 'Grade', 'meadium of instruction' if i go to sleep and comback then the dropdown is not displaying**
![Screenshot_2023-11-03-12-05-16-605](https://github.com/chimple/cuba/assets/138564361/806278e4-e193-4348-a9c7-51db30532c7a)

**2. Place holder is not displaying in the dropdown**

![Screenshot_2023-11-06-12-03-52-836](https://github.com/chimple/cuba/assets/138564361/f6c3fd8b-ba93-4bd0-9abe-803d874ee40c)

**For Example: (play store app)**

![Screenshot_2023-11-06-11-51-59-988](https://github.com/chimple/cuba/assets/138564361/cea1001c-e98a-4beb-bc82-36a049b95858)

**Comment by pratapramesh** [comment]
No issues found
