### ISSUE TITLE
Detail page of a quiz

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1009]
- [ ] Get information about the quiz
- [ ] Display the list of student's separately
- [ ] Download the lesson content and enable the join button after downloading
- [ ] After clicking on join button it should join the quiz and take to the next page

**Comment by Pramodmarssun** [comment]
- [ ] Played and Not played bar should start from starting of the screen
- [ ] In some of the device **Join Button** is out of the screen



**Screenshot**:
![Screenshot_20231221_092211_Chimple](https://github.com/chimple/cuba/assets/108517798/defef845-dac5-4b59-9c1c-c6e5706a2a16)
