### ISSUE TITLE
Display the Multiple choice questions 

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1010]
- [ ] Parse the config file and create the UI
- [ ] Capability for displaying images , audio and texts
- [ ] Clicking on any choice and determine if its correct or wrong answer. Show whether its right or wrong only after the given timeline ends [If it is Live Quiz]
- [ ] Go to next question

**Comment by Pramodmarssun** [comment]
I have thoroughly tested the 'Display the Multiple choice questions' task, and I'm pleased to report that all functionalities are working as expected. I will continue to monitor this closely and will create a bug if any issues arise during further investigation.
