### ISSUE TITLE
Leaderboard for the Quiz

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1012]
- [ ] Create a page for Room results
- [ ] Leaderboard for class results

**Comment by Pramodmarssun** [comment]
- Tested 'Room results.' Identified issue: Complete UI doesn't display as intended in room result. Once resolved, we can proceed to test other details on this screen for a comprehensive validation of the feature.
- Found an issue: scores in the room and on the leaderboard don't match for the 'Leaderboard for the Quiz' task

**Comment by Pramodmarssun** [comment]
- [ ] Quiz scores should only display whole numbers, currently showing decimals.
  - Room result
  - In detail page of quiz 

- [ ] Room result complete screen scrollable for some time.
