### ISSUE TITLE
How to trigger text to speech using capacitor

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1023]

**Comment by Ashish1998** [comment]
For some of the text in the dialogue box the TTS audio is not properly spelled.

https://github.com/chimple/cuba/assets/99384703/6d08297b-527f-4cf2-a7da-68c9c1cd2d6c


https://github.com/chimple/cuba/assets/99384703/000e6406-239f-4ede-8fa3-fed335c8ec59


https://github.com/chimple/cuba/assets/99384703/3cf487e1-6399-4c8b-937a-643f2a72422d
