### ISSUE TITLE
Animation of dialogue box becoming smaller and bigger at the beginning and end

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1024]

**Comment by Ashish1998** [comment]
- Here if we go to suggestion screen and return to home screen we are getting a glitch.
- When we give a response as yes or no the suggestion changes before the dialogue box fades away.
- Sometimes we have to click twice on "yes" or "no" option then it will show the next suggestion.

**Comment by Ashish1998** [comment]
- Here when we click on "no" option on any suggestion the next suggestion icon changes once the dialogue box pop-up again.

https://github.com/chimple/cuba/assets/99384703/b0f387ce-cbbc-47b6-b157-e87a3e5da16d

**Comment by Ashish1998** [comment]
- Here when the dialogue box becomes smaller the sentences are changing, (Both icons and sentence should not change).

- Here First time when we get the options and we click on "no" option the icons are changing properly.
But again if the same suggestion repeats then again the above issue is happening.

https://github.com/chimple/cuba/assets/99384703/0d24fa5f-a659-4ca7-a363-83d4c509ccc1

**Comment by pratapramesh** [comment]
The lesson card icons will change after Getting the popup

https://github.com/chimple/cuba/assets/138564361/43cefcd3-19ae-40e5-82c2-c565851f84f8
