### ISSUE TITLE
Remove loading overlay and replace with Ghosting

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1028]

**Comment by SWETHAKRISHNA2** [comment]
It is working now
![Screenshot_20240131_154822_Chimple](https://github.com/chimple/cuba/assets/138753773/20e5e386-7209-4231-a3dd-df05d51ff5bd)


![Screenshot_20240131_143938_Chimple (1)](https://github.com/chimple/cuba/assets/138753773/a66a2b4b-d6ee-4cd6-adf4-50570e8170c5)
