### ISSUE TITLE
Automatically App closing issue

### ISSUE THREAD

**Issue by pratapramesh** [chimple/cuba#1051]
The master's APK is closing automatically when we are using also and keep it idle also in all page

Device: Lenovo tab

https://github.com/chimple/cuba/assets/138564361/44ebf5aa-eae6-4cab-a5de-51db553a8f05

Logs: 
[app auto close logs.txt](https://github.com/chimple/cuba/files/13523590/app.auto.close.logs.txt)

**Comment by SWETHAKRISHNA2** [comment]
Automatically app is not closing in my tab.
when I played any lesson card , after finishing the lesson card 
chimple is loading in my tab to open the homepage .

![Screenshot_2024-01-25-13-13-10-481](https://github.com/chimple/cuba/assets/138753773/500ea421-0075-4e5d-b939-371e7fa6cebe)

**Comment by pratapramesh** [comment]
No issues
