### ISSUE TITLE
Getting a glitch in loading lesson card images whenever we switch between screens.

### ISSUE THREAD

**Issue by Ashish1998** [chimple/cuba#1082]
**Description** 
When we move from one screen to other for example (from subject screen to suggestion screen) we will get a glitch. Here the lesson card images and chapter images are not loading quickly.

**Screen Record** 

https://github.com/chimple/cuba/assets/99384703/7a0fa5a3-11ae-4720-8568-71ef5b9efb8d

**Comment by Pramodmarssun** [comment]
https://github.com/chimple/cuba/assets/108517798/46a8b34e-5d86-4b93-9a89-d72b243b1a96
