### ISSUE TITLE
Add Monthly Leaderboard

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1099]
The new feature to be added for the user is to view the ‘Monthly’ leaderboard

**Comment by pratapramesh** [comment]
**If i select all time in Leader board dropdown the data is not showing**

<img width="960" alt="SnapCrab_NoName_2024-1-12_12-8-21_No-00" src="https://github.com/chimple/cuba/assets/138564361/9037ff04-2692-4d00-b7d9-c43382dfd9d3">


<img width="960" alt="SnapCrab_NoName_2024-1-12_12-8-26_No-00" src="https://github.com/chimple/cuba/assets/138564361/c161b062-f7db-453c-b82c-313c22859980">

**Comment by pratapramesh** [comment]
Fixed
