### ISSUE TITLE
Choose top performers for the leaderboard

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1100]
Top performers are to be chosen based on a predefined mathematical calculation. 

 

The data that will be collected at the end of every week and at the end of every month, will be evaluated to select students who made it to the top 25% in each leaderboard. 

Students are chosen based on the time-spent and the number of lessons played every week (maximum number of streaks achieved in a week).

**Comment by pratapramesh** [comment]
No issues
