### ISSUE TITLE
Issue in Live Quiz - No internet 

### ISSUE THREAD

**Issue by Pramodmarssun** [chimple/cuba#1154]
When we click on the quiz lesson join button will keep on loading if the internet is off.

Expected Result:
The user should not be able to access the Live Quiz lesson whenever the internet is off 
Or 
We should show app is offline due to internet connectivity and only played lessons will available to play

**Comment by Pramodmarssun** [comment]
- When we click on lesson card when it is offline detail room will be keep on loading.

**Comment by Pramodmarssun** [comment]
If the internet goes in Quiz detail room next screen will be blank

**Comment by Ashish1998** [comment]
In one device if we click on join button in Quiz and turn off the internet the room screen will keep on loading 
![Screenshot_2024-02-09-12-13-24-967_org chimple bahama](https://github.com/chimple/cuba/assets/99384703/7a6a8d4a-f454-4525-a8d9-ee2eaaa8abda)
