### ISSUE TITLE
NCERT subjects are not there in 'progress report' page

### ISSUE THREAD

**Issue by pratapramesh** [chimple/cuba#1156]
'NCERT English' and 'NCERT maths' subjects are not there in Student 'progress report'

![Screenshot_2024-01-19-10-53-51-756_org chimple bahama](https://github.com/chimple/cuba/assets/138564361/719b5f97-19c7-42bd-9e51-be55af24c890)

**Comment by divyahariharan2103** [comment]
@pratapramesh Please let me know if this is still reproducible?

**Comment by pratapramesh** [comment]
@divyahariharan2103 You can close this issue
