### ISSUE TITLE
Images in the Multiple option questions are not displayed.

### ISSUE THREAD

**Issue by Ashish1998** [chimple/cuba#1158]
**Description** 
In the Avatar in assignment flow, if we keep on clicking on "No" then for the multiple option question the image will not be displayed.

**Screen Record**

https://github.com/chimple/cuba/assets/99384703/f8b52b4b-dda4-4e62-b786-976e9114b76b

**Comment by divyahariharan2103** [comment]
Re-opening this issue as it is reproducible again

**Comment by Pramodmarssun** [comment]
This is has been fixed we can move this to done
