### ISSUE TITLE
Toggle button is not working in Parent page

### ISSUE THREAD

**Issue by pratapramesh** [chimple/cuba#1178]
1. If we OFF the toggle then also we can able to hear all the music and sound
2. Toggle Allignment is not proper when we select parent language as HINDI and KANNADA 

![Screenshot_2024-01-19-16-38-45-107_org chimple bahama](https://github.com/chimple/cuba/assets/138564361/5f2b5821-2eff-45f6-8957-e89cc74eadda)

**Comment by Pramodmarssun** [comment]
Here only Music will be be turned of not instruction
