### ISSUE TITLE
Header icon allignment issue

### ISSUE THREAD

**Issue by pratapramesh** [chimple/cuba#1183]
The header icons don't have proper allignment in chapter page and lessoncard page

![Screenshot_20240119_111915_Chimple](https://github.com/chimple/cuba/assets/138564361/045f9f19-d114-4dbb-bded-7b812400e953)
![Screenshot_20240119_112219_Chimple (1)](https://github.com/chimple/cuba/assets/138564361/2192ebff-48f4-4572-a28f-e0472b6a6e24)
![Screenshot_20240119_112649_Chimple](https://github.com/chimple/cuba/assets/138564361/20dde9fa-64b6-4d48-a690-641bedfb9fc8)
![Screenshot_20240119_184950_Chimple](https://github.com/chimple/cuba/assets/138564361/2abd76c1-63b0-494e-b3e1-fe0415046390)

**Comment by Ashish1998** [comment]
This issue is fixed.

**Comment by SWETHAKRISHNA2** [comment]
The header icons are displaying properly.

![Screenshot_2024-02-19-19-05-53-802](https://github.com/chimple/cuba/assets/138753773/27296c3f-4c1c-40a2-abe7-5ed5690087cd)

![Screenshot_2024-02-19-19-06-26-425](https://github.com/chimple/cuba/assets/138753773/87eba9df-3774-4b11-b1a4-3828e10bd3fb)

**Comment by SWETHAKRISHNA2** [comment]
The header icons are displaying properly.

![Screenshot_2024-02-19-19-05-53-802](https://github.com/chimple/cuba/assets/138753773/1c491b78-2df1-4caf-b0d9-04dc7102c3a0)

![Screenshot_2024-02-19-19-06-26-425](https://github.com/chimple/cuba/assets/138753773/cb1b756e-01b1-4a90-9ce1-e0722b114867)
