### ISSUE TITLE
New assignment is not appearing in the avatar screen.

### ISSUE THREAD

**Issue by Ashish1998** [chimple/cuba#1185]
**Description** 
When we assign a new assignment, it will not show up in the avatar screen flow until we go to Homework screen and return to Home screen.

**Steps to reproduce** 
1. Assign a new home work, and open the profile in kids app.
2. Here click on let's play and go to assignment flow and check if the new home work is appearing.
3. Then switch to Homework screen and return to Home screen.

**Comment by divyahariharan2103** [comment]
Not reproducible
