### ISSUE TITLE
Grade dropdown issue

### ISSUE THREAD

**Issue by pratapramesh** [chimple/cuba#1186]
**Description:**
while creating student select 'Grade1' or 'Below Grade1' then go to chapter page there Grade drop down automatically select Grade 1. Then edit student and select  Grade 2/ Grade3 / Above Grade 3 then go to chapter page there Grade drop down not changing Grade 2 and vice versa

<img width="960" alt="SnapCrab_NoName_2024-1-19_19-35-6_No-00" src="https://github.com/chimple/cuba/assets/138564361/b96fbbbb-1fee-49f0-8b3e-14022bd3b655">

**Comment by Ashish1998** [comment]
This issue is fixed.

**Comment by SWETHAKRISHNA2** [comment]
It is working now.
![Screenshot_2024-02-14-12-38-44-801](https://github.com/chimple/cuba/assets/138753773/9538e941-d4e3-4c85-94a1-0fac5adc0191)
