### ISSUE TITLE
If we switch screens and return to Home screen Multiple option question will be displayed first.

### ISSUE THREAD

**Issue by Ashish1998** [chimple/cuba#1187]
**Description** 
From the home screen if we click on "Lets play" button and we get multiple option question, here from home screen if we switch to leader board screen and return to home screen first question will be displayed for few seconds then timer will be displayed.

**Screen record** 

https://github.com/chimple/cuba/assets/99384703/72f3ff36-dbed-492f-bb45-d8478d3fd098

**Comment by Ashish1998** [comment]
Issue is fixed.

**Comment by divyahariharan2103** [comment]
Not reproducible
