### ISSUE TITLE
Error message is not displaying completely in login page

### ISSUE THREAD

**Issue by pratapramesh** [chimple/cuba#1192]
After getting maximum otp if we try to login again, the error message is not displaying completely 

![Screenshot_2024-01-19-17-46-12-678_org chimple bahama (1)](https://github.com/chimple/cuba/assets/138564361/bf5a4e7f-cfbe-4a3d-9da1-5fb4d03532f5)

**Comment by Ashish1998** [comment]
Issue is fixed

**Comment by SWETHAKRISHNA2** [comment]
It is coming now

![Screenshot_2024-02-16-15-39-46-239](https://github.com/chimple/cuba/assets/138753773/eacc0ad7-b119-4699-8303-a18b56954e68)
