### ISSUE TITLE
Audio issue in Multiple option question which has 4 options.

### ISSUE THREAD

**Issue by Ashish1998** [chimple/cuba#1194]
**Description** 
In multiple option questions which has 4 options if we give a wrong answer then the same question will be displayed, but here the TTS audio is not playing if we give wrong answer. But in the question which have 2 options the audio plays every time we give wrong answer.

**Screen Record**

https://github.com/chimple/cuba/assets/99384703/ca42c97a-b0ac-45fb-af02-9759497eb02e

**Comment by Pramodmarssun** [comment]
TTS is playing for all the questions coming in Chatbox

**Comment by Ashish1998** [comment]
Issues is fixed.

**Comment by SWETHAKRISHNA2** [comment]
TTS audio is coming
