### ISSUE TITLE
Translation not added for timer screen and questions.

### ISSUE THREAD

**Issue by Ashish1998** [chimple/cuba#1196]
**Description**
For Hindi and Kannada language the Translations are not added in the timer screen and for some of the questions. 

![Screenshot_2024-01-20-14-33-44-75_ddc0fec0f25cadbb53407d57e5100bc9](https://github.com/chimple/cuba/assets/99384703/7aa5fe13-5e3a-4d4f-9d67-5c4aabcf1a79)
![Screenshot_2024-01-20-14-34-08-42_ddc0fec0f25cadbb53407d57e5100bc9](https://github.com/chimple/cuba/assets/99384703/d231f480-7d0b-424e-adcb-037c488f073a)
![Screenshot_2024-01-22-16-23-29-62_ddc0fec0f25cadbb53407d57e5100bc9](https://github.com/chimple/cuba/assets/99384703/5ed2186f-4845-4c70-bc95-5603bf82f4dc)

![Screenshot_2024-01-20-14-34-37-92_ddc0fec0f25cadbb53407d57e5100bc9](https://github.com/chimple/cuba/assets/99384703/c3e21b03-974b-4664-9db9-d6e1b0019062)
![Screenshot_2024-01-20-14-35-01-71_ddc0fec0f25cadbb53407d57e5100bc9](https://github.com/chimple/cuba/assets/99384703/0b1d82d9-d516-4245-b26e-6da4693786ab)

**Comment by Pramodmarssun** [comment]
When we show remaining time or the time need to be complete we are showing in student selected language. 
But for the multiple choice we are showing in English only.

**Comment by Ashish1998** [comment]
![Screenshot_2024-01-24-15-08-28-27_ddc0fec0f25cadbb53407d57e5100bc9](https://github.com/chimple/cuba/assets/99384703/60e26770-8095-4f0a-82cd-5f82e99746fd)

**Comment by Ashish1998** [comment]
The translations are added.
