### ISSUE TITLE
All Subjects are showing for NCERT Student

### ISSUE THREAD

**Issue by pratapramesh** [chimple/cuba#1197]
**Description:** While creating the student profile if user select NCERT in Board drop down then also all the subjects are displaying in Subject Page

- NCERT English and NCERT Maths lesson cards are showing just English, maths in 'Played' section
![Screenshot_20240124_130217_Chimple](https://github.com/chimple/cuba/assets/138564361/7cf21439-20a4-4caf-848a-80eb6474bfb4)

BOARD - NCERT
NCERT subjects should come with default courses
BOARD - KARNATAKA STATE BOARD
Kannada subjects with default subjects
BOARD - OTHERS
other courses except ncert and kannada
DEFAULT COURSES - english, maths, digital skills

**Comment by SWETHAKRISHNA2** [comment]
BOARD -Karntaka state

![Screenshot_2024-02-12-20-38-13-374](https://github.com/chimple/cuba/assets/138753773/c624d81f-fea3-44ca-8916-8bf3e25b4ae1)

BOARD- others


![Screenshot_2024-02-12-20-25-53-707](https://github.com/chimple/cuba/assets/138753773/990e9e82-a346-4810-9cf2-cf8c7e4fdc1e)
