### ISSUE TITLE
English audio plays for a lesson even if profile is in other language.

### ISSUE THREAD

**Issue by Ashish1998** [chimple/cuba#1199]
**Description**
Here if we click on Yes and go to lesson card from subject flow the TTS audio playing will be in English but text displayed will be in other language. This happens in both Hindi and Kannada languages.

**Steps to reproduce** 
1. Create a profile in Hindi or Kannada.
2. From Avatar/Home screen go to a course/subject in the avatar flow.
3. There click yes to go to Lesson, Subject, Yes----> Chapter, yes-----> Lesson
4. Here when it displays lesson the TTS audio will be playing in English.

**Screen Record**

https://github.com/chimple/cuba/assets/99384703/2b245460-6f65-41f3-a211-72f24c2b037c

**Comment by Pramodmarssun** [comment]
TTS audio is playing in English for the Hindi language profile. It's only happening for random question's we are showing.

**Screen recording:**

https://github.com/chimple/cuba/assets/108517798/ef7045f7-2060-419f-a0d7-e50dcad2421a

**Comment by SWETHAKRISHNA2** [comment]
TTS  audio  I selected as a language hindi , but it is coming english language 

![Screenshot_20240124_175604_Chimple](https://github.com/chimple/cuba/assets/138753773/bc3dccbf-2e9c-4ba6-b633-6d3788b09982)

![Screenshot_20240124_175635_Chimple](https://github.com/chimple/cuba/assets/138753773/8f311087-b75b-4cc6-a765-091bfe14fc04)

![Screenshot_20240124_175659_Chimple](https://github.com/chimple/cuba/assets/138753773/385ee6ee-73c0-43ea-9406-b2da85ddd763)

**Comment by Ashish1998** [comment]
Issue is fixed.
