### ISSUE TITLE
Audio of TTS plays even when app is running in background.

### ISSUE THREAD

**Issue by Ashish1998** [chimple/cuba#1213]
**Description**
Audio of the TTS keeps on playing even if we close the app.

**Screen Record**

https://github.com/chimple/cuba/assets/99384703/03beb5c1-0f94-451b-86c0-28df52e8cfb1

**Comment by Pramodmarssun** [comment]
This issue is still happening

**Comment by SWETHAKRISHNA2** [comment]
the audio of TTS it is keeping on playing when I click the sleep mode also

**Comment by Pramodmarssun** [comment]
Still audio will be playing in background if we close the app

**Comment by pratapramesh** [comment]
Issue is still there

**Comment by pratapramesh** [comment]
while playing the audio, close the app and open it in background, there if we click on that audio button the audio is not playing

https://github.com/chimple/cuba/assets/138564361/ecad3f6d-57aa-434e-bf6c-45a606c3751a

**Comment by pratapramesh** [comment]
Issue is fixed
