### ISSUE TITLE
Question board translation issue in Coco's Game

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1232]

**Comment by Ashish1998** [comment]
Still for few questions and for most of the options the translations are not present.

![Screenshot_2024-01-31-12-39-21-18_ddc0fec0f25cadbb53407d57e5100bc9](https://github.com/chimple/cuba/assets/99384703/51eae839-dc1f-4313-a895-053c2ec161ac)

The following sheet has the list of lessons and level where translation is not present,
https://docs.google.com/spreadsheets/d/1mbC6MIbOrontdrprmt6yflt0zC9kqYTY35efvlJFjSg/edit?usp=sharing

**Comment by SWETHAKRISHNA2** [comment]
I selected as a hindi language , it is working now
![Screenshot_2024-02-07-14-37-03-423](https://github.com/chimple/cuba/assets/138753773/e65e89af-de3d-4f1a-ae7e-cacb98f238e3)

**Comment by SWETHAKRISHNA2** [comment]
some levels english translation is showing 
1. subtraction1-  3, 7th levels.
2. subtract1- 3, 4 th levels
3. Howmany- 1, 5 th levels
4. subtraction challenge- 4,6th levels
5. Multiplication1 - 3rd level
6. Multiplication 2-   2,3,4,5,6,7 th levels
![Screenshot_2024-02-22-16-07-21-612](https://github.com/chimple/cuba/assets/138753773/10f85272-18f2-4432-b2a9-01469ae25c27)

**Comment by SWETHAKRISHNA2** [comment]
howmany?--     3rd  level
![Screenshot_2024-02-26-15-02-25-242](https://github.com/chimple/cuba/assets/138753773/b508df2e-be8f-4b9a-80c6-6bbad09c1dbf)
subtraction challenge  - 4, 6,7 th levels
![Screenshot_2024-02-26-15-26-41-669](https://github.com/chimple/cuba/assets/138753773/e68d95cc-fb79-46d5-ab5c-3dbef9c90ac4)

multiplication 1- 3rd level
![Screenshot_2024-02-26-15-32-44-575](https://github.com/chimple/cuba/assets/138753773/483d548f-2885-4819-a8d4-80098963c52b)
Multiplication 2 ===  2,4,7 th levels

**Comment by SWETHAKRISHNA2** [comment]
Even I played every one some lesson card but stars are not coming .
![Screenshot_2024-02-26-15-54-55-392](https://github.com/chimple/cuba/assets/138753773/54151dd3-0396-4184-b631-fd9fd15e882e)
