### ISSUE TITLE
Avatar timer issue

### ISSUE THREAD

**Issue by pratapramesh** [chimple/cuba#1247]
Avatar Timer is showing the time as 80 sec, 90 sec

**Steps to Reproduce:**

1. Click on lets play button in Avatar
2. Play the 1st and 2nd lesson card 

![Screenshot_2024-02-05-15-15-36-105](https://github.com/chimple/cuba/assets/138564361/386a7fd3-6663-4f8d-9500-9bd72de90e66)

**Comment by SWETHAKRISHNA2** [comment]
Avatar timer is not showing 80 & 90 sec , when I played some lesson card.

![Screenshot_2024-02-14-14-43-44-627 (1)](https://github.com/chimple/cuba/assets/138753773/ee724fec-86a3-4444-953f-b9a312537f7c)








![Screenshot_2024-02-14-13-06-28-789](https://github.com/chimple/cuba/assets/138753773/d6988465-d27b-4efd-84ea-0e9df3a4848f)

**Comment by Ashish1998** [comment]
This issue is fixed.
