### ISSUE TITLE
The Orientation of the Images and buttons on the dialogue box will change. 

### ISSUE THREAD

**Issue by Ashish1998** [chimple/cuba#1248]
**Description**
In the Avatar dialogue box when we click on the "No" option it will show the next suggestion but when the flow changes or when we get multiple option question the images and the buttons position will change.

**Steps to reproduce**
1. Go to a profile and go to Avatar screen.
2. Here click on "No" button, and go to different suggestions.

**Screen Record** 

https://github.com/chimple/cuba/assets/99384703/88a1ca7a-e080-4f60-98bf-37db6632c665

**Comment by Ashish1998** [comment]
Here if we keep on clicking "No" then the images of the lesson cards will not be displayed on the dialogue box. 

https://github.com/chimple/cuba/assets/99384703/6d2d374f-5339-4937-9515-82a4977f92cc

**Comment by SWETHAKRISHNA2** [comment]
when I click on NO   then the homepage  is not displaying in blank screen.

![Screenshot_20240305_160004_Chimple](https://github.com/chimple/cuba/assets/138753773/417d853c-da0b-4638-9913-48b461d6c43b)
