### ISSUE TITLE
Translate the WhatsApp chatbot to Kannada

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1273]

**Comment by pratapramesh** [comment]
1. Student progress report is showing like this
![WhatsApp Image 2024-02-19 at 2 09 31 PM](https://github.com/chimple/cuba/assets/138564361/e7326d8c-15c3-41f0-bc9e-fd8136b379b5)

2. If no student complete homework then we generate student report, it is showing english text
<img width="960" alt="SnapCrab_NoName_2024-2-19_12-7-52_No-00" src="https://github.com/chimple/cuba/assets/138564361/8da18fb0-6f29-4a25-a26f-78b94bd58909">


3. These options not displaying completely so i have reduced text length in sheet, you can replace the text

<img width="960" alt="SnapCrab_NoName_2024-2-19_12-1-15_No-00" 
src="https://github.com/chimple/cuba/assets/138564361/138255b6-0e87-4f78-9e3b-90c2ab9da523">

**Comment by pratapramesh** [comment]
**Unable to generate the Report**

**Comment by pratapramesh** [comment]
No issues
