### ISSUE TITLE
Issue in opening subject screen in offline after few days 

### ISSUE THREAD

**Issue by Pramodmarssun** [chimple/cuba#1277]
**Description:**
When we open the subject screen offline after 2 or 3 days it will be keep on loading for a long time and it will display a blank screen.

**Log's:**
[Subject screen after few days in offline .txt](https://github.com/chimple/cuba/files/14275039/Subject.screen.after.few.days.in.offline.txt)

**Comment by SWETHAKRISHNA2** [comment]
after testing the offline subject screen , even I played some lessons it will take 2-3 days

**Comment by pratapramesh** [comment]
No issues
