### ISSUE TITLE
Language drop down not appearing in offline mode.

### ISSUE THREAD

**Issue by Ashish1998** [chimple/cuba#1285]
**Description** 
In offline mode the language dropdown is not displaying it shows empty screen.

**Screenshot** 
![Screenshot_2024-02-15-14-23-52-56_ddc0fec0f25cadbb53407d57e5100bc9](https://github.com/chimple/cuba/assets/99384703/1703fcc5-405f-4904-9e53-a714be9eaf92)

**Comment by SWETHAKRISHNA2** [comment]
it is coming

**Comment by SWETHAKRISHNA2** [comment]
It is coming

![Screenshot_20240228_161550_Chimple](https://github.com/chimple/cuba/assets/138753773/2c8a5503-72b0-482d-8ab5-2dac04ebe880)
