### ISSUE TITLE
MCQ questions appears before the timer after playing a lesson.

### ISSUE THREAD

**Issue by Ashish1998** [chimple/cuba#1296]
**Description**
In the Avatar screen if we switch some suggestions and play a lesson after we complete it, in the Avatar screen the Multiple option question will appear and then it will change to timer on the dialogue box.

**Steps to reproduce**
1. In Avatar screen click on "No" for 2 or 3 suggestions.
2. Then play a suggestion in that screen.
3. After completing we will be directed to Avatar screen here First MCQ questions will appear first.

**Screen Record**

https://github.com/chimple/cuba/assets/99384703/e3f14fab-72d1-4647-a608-a08767f2e20d

**Comment by pratapramesh** [comment]
No issues
