### ISSUE TITLE
Add details on the gamify time spent page

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1304]
In the gamified time spent feature add the following text :
"Playing for 10 minutes each week will enhance your school homework practice and increase your chances of winning rewards"

<img width="1364" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnk5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38cd71d512437690a77f1d115cc2bb54ce210006/image%20%285%29.png" alt="image (5).png" />

**Comment by pratapramesh** [comment]
Displaying old text
![Screenshot_2024-03-11-12-18-52-957](https://github.com/chimple/cuba/assets/138564361/c96cb7e1-f351-4f6c-a979-764b6e7ffd6f)

**Comment by pratapramesh** [comment]
![screenshot_20240319_165117_chimple](https://github.com/chimple/cuba/assets/138564361/c3a7cc59-9fc1-4a1a-89fe-20e1b22960cb)


![screenshot_20240319_165104_chimple](https://github.com/chimple/cuba/assets/138564361/7369af8d-e519-43ba-87ec-529a5f01812b)

**Comment by pratapramesh** [comment]
No issues
