### ISSUE TITLE
Lessons data not updating in cuba if we play from Avatar screen.

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1322]
**Description** 
Any number of lessons or assignments we play through Avatar screen, in teacher app if we go that profile some of the played lessons are not displaying.

![Screenshot_2024-02-15-14-50-22-27_ddc0fec0f25cadbb53407d57e5100bc9](https://github.com/chimple/malta/assets/99384703/97391359-d85c-4c60-af8a-fd9e63a03cc2)
![Screenshot_2024-02-15-14-50-54-62_ab713fc9608771221b283703fb42cd3f](https://github.com/chimple/malta/assets/99384703/dea8606b-dc20-41ef-9fd2-5ef8f565e981)

**Comment by pratapramesh** [comment]
Here i played two assignment lessoncards in avatar page but in malta it is showing only assignment

![Screenshot_2024-03-12-12-14-41-821 (1)](https://github.com/chimple/cuba/assets/138564361/077af705-1f1b-4723-9cd2-7748bef5a7c3)

![Screenshot_2024-03-12-12-14-54-401 (1)](https://github.com/chimple/cuba/assets/138564361/5812e7cb-65cf-4141-b9ea-f1ccb9723a32)
![Screenshot_2024-03-12-12-15-05-166 (1)](https://github.com/chimple/cuba/assets/138564361/3d3fda2a-29f9-475c-b07d-ea34cc99b362)

**Comment by Pramodmarssun** [comment]
When we play assignment from avatar screen it's updating in different grade 
I have assigned 2 lesson's of Grade 1 English but it's coming under Grade 2 English in teacher app

**Comment by Pramodmarssun** [comment]
This is working and we can move it to done
