### ISSUE TITLE
Lesson data is not coming under student profile in database 

### ISSUE THREAD

**Issue by Pramodmarssun** [chimple/cuba#1350]
**Description:** 
When we play and finish downloaded homework, then later connect to the internet, the lesson data will be stored in the database but won't show up under the student's profile.

**Step's to reproduce the issue** 
1. Download some 20 home work in home work screen
2. Turn of the internet once all lesson's downloaded 
3. open next day and play few lesson's without turning on internet 
4. Do above step for 4 days and turn on the internet for device 
5. Here Data will not show under the student profile data base

**Comment by divyahariharan2103** [comment]
Duplicate task of 1380
