### ISSUE TITLE
Create the Class summary header

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1355]
Number of students , number of tasks etc

**Comment by RadhaG3** [comment]
**User Story**
As a Teacher, I should be able to add a subject. On the same page, an option to delete a subject.

**Acceptance Criteria**
(i) _Given that_ user navigates to 'Add Subject' on a subject page
Menu -> Classroom -> Subjects

_When_ clicked on 'Add Subject',
_Then_ User to choose the available subjects to add

(ii) _Given that_ user chooses to 'Delete Subject' on a subject page
_When_ User chooses to 'Delete Subject',
_Then_ a subject to be deleted

**Comment by divyahariharan2103** [comment]
Closing the task as it will no longer be required as per new Malta migration mockups
