### ISSUE TITLE
Dropdown details for individual students

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1357]

**Comment by RadhaG3** [comment]
**User Story**
As a Teacher, I should be able to view weekly and monthly activities of a student. 

**Acceptance Criteria**
(i) Given that user navigates to 'Home Page', and chooses weekly option from the dropdown. 
When 'Weekly' option is chosen from the dropdown,
Previous week's data to be displayed. Also, user could view all the weeks before the previous week by scrolling backwards.
Then User to choose a student to see all the activities for a chosen week. A dropdown to show the assignments, and the color coded scores for each day.



(ii) Given that user navigates to 'Home Page', and chooses monthly option from the dropdown. 
When 'Monthly' option is chosen from the dropdown,
Previous month's data to be displayed. Also, user could view all the months before the previous month by scrolling backwards.
Then User to choose a student to see all the activities for a chosen month. A dropdown to show the assignments, and the color coded scores for each month.
<img width="507" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelE1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e06e9e19b1677851b66ff892623da5a4b0efc323/Individual%20Dropdown.png" alt="Individual Dropdown.png" />
<img width="503" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejA1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e121d254d9e78e59f4ebcc5ed24370912b30819f/Monthly%20Individual%20DD.png" alt="Monthly Individual DD.png" />

**Comment by pratapramesh** [comment]
No issues
