### ISSUE TITLE
Report functionality

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1358]
Send report as an image

**Comment by RadhaG3** [comment]
**User Story**
As a Teacher, I should be able to send a Report. Reports such as **Weekly**, **Monthly**, **Assignments**, **Quiz**

**Acceptance Criteria**
(i) _Given that_ user navigates to 'Add Subject'  on a subjects page
  Slider-> Classes -> Subjects
_When_ clicked User chooses to add a subject
_Then_ User to confirm to add


<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM210QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f44e805ff1485733e88c4c50553781203d179bb/image.png" alt="image.png" />

**Comment by RadhaG3** [comment]
**User Story**
As a Teacher, I should be able to send a Report. Reports such as **Weekly**, **Monthly**, **Assignments**, **Quiz**

**Acceptance Criteria**
(i) _Given that_ user navigates to 'Add Subject'  on a subjects page
  Slider-> Classes -> Subjects
_When_ clicked User chooses to add a subject
_Then_ User to confirm to add


<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM210QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f44e805ff1485733e88c4c50553781203d179bb/image.png" alt="image.png" />

**Comment by pratapramesh** [comment]
1. Toggle button allignment issue and its not working and text is not changing to all activities
![Screenshot_2024-11-21-16-28-50-165](https://github.com/user-attachments/assets/2e0977f7-903b-47ff-a252-201c6966109e)

2. date range allignment is not consistant

https://github.com/user-attachments/assets/d4312809-d989-4f67-8992-6697d59c14a2


3. Dropdown size is larger all page
![Screenshot_2024-11-21-16-34-21-784](https://github.com/user-attachments/assets/ade53381-d1ab-44cf-becf-5223f70e7e82)

4. Grade is not mentioned in subject dropdown
![Screenshot_2024-11-21-16-34-02-350](https://github.com/user-attachments/assets/93762885-bde4-40af-a7de-78b06aff12dc)

5. Name is missing for dropdown
![Screenshot_2024-11-21-20-18-19-158](https://github.com/user-attachments/assets/4bd257b9-af6c-409e-94ac-f5912aadb83e)

6. View progress is not naviagting to progress page
![Screenshot_2024-11-21-19-31-47-667](https://github.com/user-attachments/assets/a6b90910-0620-43ec-923d-6ec4fa610319)

7. View progress button colour is too dark
<img width="960" alt="SnapCrab_NoName_2024-11-22_9-18-54_No-00" src="https://github.com/user-attachments/assets/7ea81d9b-d2d2-4c48-bd1e-da461ad7b8d8">

8. Assignment assigned/completion date is missing
![Screenshot_2024-11-21-16-28-50-165](https://github.com/user-attachments/assets/d6dff0a8-22c4-4e53-817f-84dc9839b31f)

9. Assigned date and played date is not matching
![Screenshot_2024-11-21-20-36-09-877](https://github.com/user-attachments/assets/165fd6d7-17e1-405b-81ca-eb93616d56f1)
![Screenshot_2024-11-21-20-34-12-091](https://github.com/user-attachments/assets/c5fcfafb-ee36-455f-be78-949a5ebff828)

10. date and name is overlapping and in other page chapter name is not displaying completely
<img width="960" alt="SnapCrab_NoName_2024-11-21_20-44-9_No-00" src="https://github.com/user-attachments/assets/311cced0-a0c4-4c05-abc7-afae1f472681">

**Comment by pratapramesh** [comment]
1. toggle button allignment is not consistant

https://github.com/user-attachments/assets/83d27fe0-7807-4d29-b901-2db362b9a20d

2. Student name is moved to left side

<img width="960" alt="SnapCrab_NoName_2024-11-27_19-19-49_No-00" src="https://github.com/user-attachments/assets/f6fb5e75-9bd1-4bc4-8140-bd99e8865513">

3. in chapter page the last student data is not visible
<img width="960" alt="SnapCrab_NoName_2024-11-28_9-25-22_No-00" src="https://github.com/user-attachments/assets/5faa090d-535c-4eaa-8b9b-8dfc28c60ee1">

**Comment by pratapramesh** [comment]
No issues
