### ISSUE TITLE
Teacher's Profile 

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1361]

**Comment by RadhaG3** [comment]
**User Story**
As a Teacher, I should be able to view/edit my  profile.

**Acceptance Criteria**
(i) Given that user navigates to 'Teacher's' page
Menu -> Classroom -> Class -> Teachers
When clicked on a chosen Teacher,
Then User to view the Teacher's profile
The page displays,

Teacher's Name
School
Class
Phone

The above details to be available to edit if required

<img width="467" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3B3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--83333370c6c217a180faf36eaf4caef1466e7699/Teacher%27s%20Profile.png" alt="Teacher's Profile.png" />

**Comment by pratapramesh** [comment]
- Here Teacher Name, Email id, edit option, Upload profile photo, logout, delete account button is not present
- School, class, phone texts are not present
- In each textfeild we can enter Alphabets, numbers, special characters

**Comment by pratapramesh** [comment]
1. Not able to Edit email-id and phone number
![Screenshot_20241007_081015](https://github.com/user-attachments/assets/9922841e-5ef2-4990-8ba3-9d29587fd7fc)

2. Dropdown UI is different in mobile and tab
![Screenshot_2024-10-04-12-14-49-288](https://github.com/user-attachments/assets/1ce20adb-b49c-466e-a800-5af6649fb064)
![Screenshot_20241004_121446](https://github.com/user-attachments/assets/ea604b7e-7dac-440b-b87d-0eee047b5407)

3. Without clicking on edit if i click profile image it's navigating to gallery

https://github.com/user-attachments/assets/4beebbb2-f103-40f3-8935-0a5bcf8ca7cb

**Comment by pratapramesh** [comment]
1. Edit icon is missing when the user name is long
![Screenshot_20241015_085208](https://github.com/user-attachments/assets/2c876063-3be5-46e7-a042-02bdc4cbb859)
2. Dropdown UI is not same in mobile and tab

**Comment by pratapramesh** [comment]
Dropdown is overlapping

https://github.com/user-attachments/assets/8ef3542f-8058-417a-bf81-f0be83e47e93

**Comment by pratapramesh** [comment]
![Screenshot_2024-10-30-10-02-54-002](https://github.com/user-attachments/assets/a1f31e5d-0d5e-4de9-9b29-5d6b973cc6aa)

**Comment by pratapramesh** [comment]
No issues
