### ISSUE TITLE
School profile

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1362]

**Comment by RadhaG3** [comment]
**User Story**
As a Teacher, I should be able to add a school. On the same page, an option to edit/delete a school.

**Acceptance Criteria**
(i) Given that user navigates to 'Add School' page from dropdown menu 
Menu -> Classroom -> School
When clicked on 'Add school',
Then User to enter the below details

- School Name
- City
- State


(ii) Given that user navigates to 'Switch School' button on a school page
When clicked on 'Switch School',
Then User to choose a school from the available schools

(iii) Given that user navigates to 'Delete School' button on a school page
When User chooses to 'Delete school',
Then current school to be deleted
<img width="489" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzA1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b161559f8e7696e5fd6969a1e19f9d7cf56191d/Add%20School.png" alt="Add School.png" />

**Comment by Pramodmarssun** [comment]
1. School Names are not displaying 

![Screenshot_20240909_092450_Chimple](https://github.com/user-attachments/assets/e81dd377-554b-449e-9093-d60bef87d421)

2. Once we add school name and information of school once we click on save, we don't get to know school is created or creating, this can lead confusion and if we click on save button back to back it is creating multiple school with same school name


https://github.com/user-attachments/assets/6646d310-6115-43b5-af25-eecd77ff05ae
