### ISSUE TITLE
Add class

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1363]

**Comment by RadhaG3** [comment]
**User Story**
As a Teacher, I should be able to add a class. On the same page, an option to switch between classes and to delete a class.

**Acceptance Criteria**
(i) _Given that_  user navigates to 'Add Class' button on a class page
_When_ clicked on 'Add Class',
_Then_ User to enter the below details

- Class Name

(ii) _Given that_  user navigates to 'Switch Class' button on a class page
_When_ clicked on 'Switch Class',
_Then_ User to choose the available classes

(iii) _Given that_  user navigates to 'Delete Class' button on a class page
_When_ User chooses to 'Delete Class',
_Then_  class to be deleted

**Comment by RadhaG3** [comment]
<img width="487" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjBqQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--93f407e53d6806d6fcb4b8ec4405d4ef407e2001/Add%20Class.png" alt="Add Class.png" />
