### ISSUE TITLE
Add subject

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1364]

**Comment by RadhaG3** [comment]
**User Story**
As a Teacher, I should be able to add a subject. On the same page, an option to delete a subject.

**Acceptance Criteria**
(i) Given that user navigates to 'Add Subject'
button on a class page
When clicked on 'Add Class',
Then User to enter the below details

Class Name
(ii) Given that user navigates to 'Switch Class' button on a class page
When clicked on 'Switch Class',
Then User to choose the available classes

(iii) Given that user navigates to 'Delete Class' button on a class page
When User chooses to 'Delete Class',
Then class to be deleted
<img width="482" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMndqQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c753abb3674d9c4f95d994024da8a6da22d1ca03/Add%20Subject.png" alt="Add Subject.png" />

**Comment by Pramodmarssun** [comment]
1. We are not able to add course indivisual. If we select Grade1 course, Grade 2 will also be selected autometically 
Logs: [Multiple course selected.txt](https://github.com/user-attachments/files/17056416/Multiple.course.selected.txt)


2. Not able to add course to class, once we select and confirm we can see courses added but when we click on back button and come back to added course screen we can see displaying **No selected courses added**
Logs:[No able to add course.txt](https://github.com/user-attachments/files/17056490/No.able.to.add.course.txt)

**Comment by Pramodmarssun** [comment]
- Selecting of course which is the last of the list is difficult, we are not able to click for one time we have to try multiple times clicking on it to select
- When we add or remove the courses for the particular class same functionality will happen for remaining classes of the school
- Addes courses to class is not coming in dashboard of the app properly 
- When we are loggedin with two devices with same account and when we add or remove the courses in one devices, to reflect these changes we have to reopen the app in other device

**Comment by Pramodmarssun** [comment]
When we uncheck the courses and confirm we can see courses has been removed but when we switch screen and come back, removed courses are displaying

**Steps to reproduce:**
1. Select class
2. click on Subject icon in class
3. Click on add subject icon
4. uncheck the courses which is added already 
5. confirm and click on back button 
6. Here we can see unchecked subject has been removed 
7. But when we click on back button and come back to subject screen we can see the removed courses

**Comment by Pramodmarssun** [comment]
When we click on add subject button and if we uncheck already added subject and confirm, unchecked subject shoud be removed from the class but subjects are not removed here

**Comment by Pramodmarssun** [comment]
The checkbox for selecting subjects to add to classes works, but unchecking a subject doesn't remove it from the class.

https://github.com/user-attachments/assets/99f3e5b2-f144-49e9-b8e5-9bbeea132c98

**Comment by Pramodmarssun** [comment]
1. Remove course confirmation button alignment issue
![remove course](https://github.com/user-attachments/assets/c5a91e12-24d1-4d28-840e-4eb88648b880)

2. This is how courses are listed now, should we list these courses in order 
![Screenshot_20241017_152543_Chimple](https://github.com/user-attachments/assets/7b4c22a1-cfc2-4207-8fed-1004bf5197aa)
![Screenshot_20241017_152549_Chimple](https://github.com/user-attachments/assets/d0552dcb-ba07-46f1-9c97-4b47d19039b1)

**Comment by Pramodmarssun** [comment]
Course order now 
- Chimple Grade 1
- Chimple Grade 2
- Chimple below grade 1
- Karnataka state Grade 1
- Karnataka state Grade 2
 - NCERT Grade 2 
- NCERT Grade 1

**Comment by Pramodmarssun** [comment]
We can move this story to done.
