### ISSUE TITLE
Add students

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1365]

**Comment by RadhaG3** [comment]
**User Story**
As a Teacher, I should be able to add students to my class. Also, I should be able to edit/delete any relevant information related to my students if required so that I can manage my students.

**Acceptance Criteria**
_Given_ that there is a 'Add Student' button on the add students page
_When_ clicked on 'Add Student',
_Then_ User to enter the below details

1. Student Name
2. Age
3. Student ID
4. Gender

**Comment by divyahariharan2103** [comment]
Add student ID and phone number

**Comment by pratapramesh** [comment]
- Student Name, Class, Age, Student ID, Student Number, Gender Texts are not present
- Here we can enter Age in negative values like 0, -1, -2, -3
- In class dropdown the options are not there
- Save button is missing
- In each textfeild we can enter Alphabets, numbers, special characters

https://cuba-stage-dev.web.app/storybook/?path=/docs/components-malta-addstudent-addstudentsection--docs

**Comment by Pramodmarssun** [comment]
PR not mergerd moving back to inprogress

**Comment by Pramodmarssun** [comment]
1. we can add  student name, age, student ID, Language and Gender after that we can't add student to the class 


https://github.com/user-attachments/assets/6f1f0f73-dd22-4cf5-9f28-8be1005cea6d

**Comment by Pramodmarssun** [comment]
Log's: 
[add student.txt](https://github.com/user-attachments/files/16925662/add.student.txt)

**Comment by Pramodmarssun** [comment]
1. We are not able to add student to class, add button is not working 
Logs:[Add student.txt](https://github.com/user-attachments/files/17056623/Add.student.txt)

2. In age text field we can enter more than 3 digit number

**Comment by Pramodmarssun** [comment]
- After completing the student profile creation Display picture is broken image
- Still we can add more digits in Age text field 
- Student ID is not displaying in Student profile
- we are not able to edit student profile

**Comment by Pramodmarssun** [comment]
- User can create a student without any student information 
- Student ID is still not dispalying
- After completing the student profile creation Display picture is broken image
-  Delete student is not working

**Comment by Pramodmarssun** [comment]
Add student button functionality is not working

**Comment by Pramodmarssun** [comment]
1. Student profiles flicker on the dashboard when the teacher or principal adds students to the class.
2. The "Add Student" button is disabled during student creation, even when all info is filled in, unless the language is rechanged.
3. No confirmation pop-up appears when deleting a student; they are deleted immediately upon clicking "Delete."
4. The user can't select a photo while creating a student for the class.
5. When logged in with the same user ID on multiple devices, adding a student on one device doesn't reflect on the other device.
6. When the teacher and principal are connected to the same class, if one adds a student, it doesn't reflect for the other user.

**Comment by Pramodmarssun** [comment]
- After clicking on Add stuent button it will take around 10sec to create a student profile, this will happen only when we are creating a profle with display picture 
- Still we can reproduce the drop-down overlapping issue only when we are creating a student profile when display picture is selected

**Comment by Pramodmarssun** [comment]
- We can see some shadow when we open the drop-down down arrow is in middle of the drop-down
![Screenshot_2024-10-29-12-39-43-823](https://github.com/user-attachments/assets/889ffdab-e286-41bf-af6b-ba0f9ee02f9b)

- If we click on drop-down and if we click back button, we can see drop-down overlapping 
![Screenshot_2024-10-29-14-21-50-370](https://github.com/user-attachments/assets/6d6ea662-6190-4b73-ba34-807df3bb5bcf)

**Comment by Pramodmarssun** [comment]
Drop-down is not displaying properly 
![Screenshot_2024-10-30-12-38-06-219](https://github.com/user-attachments/assets/ae03aa36-451d-4bb3-9d97-9d1db95babd6)
![Screenshot_2024-10-30-12-37-35-559](https://github.com/user-attachments/assets/234b4066-9a9c-4dc4-b923-e622d536fedf)

**Comment by Pramodmarssun** [comment]
This is how it looks now 
![Screenshot_20241107_094155_Chimple](https://github.com/user-attachments/assets/298696e3-1d03-4205-9ac4-0dd106781931)
![Screenshot_20241107_094214_Chimple](https://github.com/user-attachments/assets/b77368c2-c7bd-4e2d-8802-1dbd88c5c2a2)

**Comment by Pramodmarssun** [comment]
We can move this story to done
