### ISSUE TITLE
School / Class / Subject List 

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1370]

**Comment by RadhaG3** [comment]
**User Story**
As a Teacher, I should be able to add/edit/delete school, class and subjects.

**Acceptance Criteria**
(i) _Given That_ user navigates to 'School' page
Menu -> Classroom -> School 
_When_ clicked on School
_Then_ User to view the current school that they have registered to
The page displays,

Teacher's Name
Class Name
School Name
City
State

1. User to switch school if required by choosing from the available schools


2. User to add school by clicking 'Add School' 
Below details to be entered

- School Name
- City
- State

3. User to edit school by clicking edit icon next to School Name
Below details to be edited

- School Name
- City
- State


(ii) Given That user navigates to 'Class' page
Menu -> Classroom -> School
When clicked on School
Then User to view the current school that they have registered to
The page displays

**Comment by divyahariharan2103** [comment]
Not required as part of new mock up
