### ISSUE TITLE
View Student profile

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1371]
There are separate issues for:

1. Edit Profile
2. Delete Profile
3. View Progress

**Comment by pratapramesh** [comment]
- Student name, edit option, upload profile photo options are not present
- Student Name, School, Class, Gender, Age text is not present
- Instead of Student ID, Student Number it's showing 'Class code'
- In each textfeild we can enter Alphabets, numbers, special characters

**Comment by pratapramesh** [comment]
Now we can View the profile but can't Edit, Delete, View the progress
