### ISSUE TITLE
Not able to play lesson in avatar screen

### ISSUE THREAD

**Issue by Pramodmarssun** [chimple/cuba#1376]
**Description:**
After completing the lesson in avatar screen next lesson is not playable after clicking Yes button back to back also

**Step's**
1. Create a new profile 
2. Connect to any school 
3. In avatar screen play suggested lesson A
4. Complete the lesson and Click on yes button for Lesson B 
5. Here again and again lesson be will be keep on showing 

**Log's**
[Avatar-not able to play the lessons.txt](https://github.com/chimple/cuba/files/14769571/Avatar-not.able.to.play.the.lessons.txt)

**Rerecording** 

https://github.com/chimple/cuba/assets/108517798/45e170ab-acf2-4302-a54d-445dbd94b43d

**Comment by Ashish1998** [comment]
This issue is fixed.
