### ISSUE TITLE
To provide support for student login based on student ID when creating student profiles in script

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1389]

**Comment by SWETHAKRISHNA2** [comment]
![Screenshot_2024-04-04-14-27-43-404](https://github.com/chimple/cuba/assets/138753773/a0c884c8-000e-41c2-99ea-f4bd8b7a4e81)



![Screenshot_2024-04-04-14-25-28-510](https://github.com/chimple/cuba/assets/138753773/fce1150d-3a2a-4113-a20f-84ce7340824b)
