### ISSUE TITLE
Text changes needed in the end of assignment pop up

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1426]
The texts needs to be changed as below in Hindi:

1. Khel ki Tarah to be changed as
2. Khelna jaari rakhein to be changed to "सीखना जारी रखें।"

<img width="1822" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmg5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac2e13731f92ccf603d15e4064e24b927ad57331/Screenshot_2024-04-22-10-26-44-818_org.chimple.bahama.jpg" alt="Screenshot_2024-04-22-10-26-44-818_org.chimple.bahama.jpg" />

**Comment by pratapramesh** [comment]
**Text is not changed to "सीखना जारी रखें।"**

![Screenshot_2024-05-19-20-10-03-058](https://github.com/chimple/cuba/assets/138564361/ff2a03a6-4d86-4e52-b112-a6100319510c)

**Comment by pratapramesh** [comment]
Fixed
![Screenshot_2024-05-20-12-16-35-056](https://github.com/chimple/cuba/assets/138564361/e270281f-dee3-42eb-afa1-1bdb4619eab0)
