### ISSUE TITLE
Issue in WA chatbot 

### ISSUE THREAD

**Issue by Pramodmarssun** [chimple/cuba#1427]
Description:
No response from chatbot when there are no school's

**Comment by Ashish1998** [comment]
- Here for NCERT course name spelling needs to be added.
![Screenshot_2024-04-25-12-16-12-66_6012fa4d4ddec268fc5c7112cbb265e7](https://github.com/chimple/cuba/assets/99384703/b2aab87a-3f3a-4fc8-a4cb-70bd1ea7595d)

- There is a spelling mistake in the first option in Kannada language.
![Screenshot_2024-04-25-14-09-45-27_6012fa4d4ddec268fc5c7112cbb265e7](https://github.com/chimple/cuba/assets/99384703/da602800-882b-4b7f-8aeb-36cea0a50aa9)

**Comment by Pramodmarssun** [comment]
If the user is not connected to any school we will get this message, in this we are asking user to click on the link but we don't have one.

**"Hello There ! You are not registered with us 🙁, please click on the link to Register with Chimple. Our team will contact you shortly.."**

**Comment by Pramodmarssun** [comment]
we can move this story to done.
