### ISSUE TITLE
In offline if we try to join a class we are getting "Firebase error" message

### ISSUE THREAD

**Issue by Ashish1998** [chimple/cuba#1440]
**Description**
In offline mode if we try to join a class in homework screen we will get a error message which says "Firebase error". error message needs to be added.

**Screenshot**
![Screenshot_2024-04-29-15-40-45-71_ddc0fec0f25cadbb53407d57e5100bc9](https://github.com/chimple/cuba/assets/99384703/6b0ef233-c0cd-406c-882c-5f150585ed64)

**Comment by divyahariharan2103** [comment]
Re-estimating to 1.5 days , as it was extended
