### ISSUE TITLE
Loading issue in Avatar screen.

### ISSUE THREAD

**Issue by Ashish1998** [chimple/cuba#1449]
**Description**
After installing the app when we open the app, login and select the profile there it takes more time to load the dialogue box first and then again it takes time to load the avatar animation.
(In Lenovo tabs it takes almost 15-20  seconds to load the dialogue box itself)

This happens even when we switch to a different screen and return to the avatar screen.

**Screen Record**

https://github.com/chimple/cuba/assets/99384703/2bd71fe8-1dc8-46fa-86bd-34ee1fc832d7

**Logs** 
[Logs for dialogue box  loading.txt](https://github.com/chimple/cuba/files/15197081/Logs.for.dialogue.box.loading.txt)

**Comment by Pramodmarssun** [comment]
Whenever Avatar screen opens it's loading chatbox twice 

https://github.com/chimple/cuba/assets/108517798/64e5430d-b720-4f87-b024-d35d8e7d5d55

**Comment by Pramodmarssun** [comment]
Loading twice is fixed. we can move this to done
