### ISSUE TITLE
'Add Subject' button issue

### ISSUE THREAD

**Issue by pratapramesh** [chimple/cuba#1466]
**Create a new profile and play any lesson card then 'Add Subject' button disappeared**

https://github.com/chimple/cuba/assets/138564361/2934e6fb-a9d8-4e80-9380-fed57aac4f6f

[logs for Add subject button.txt](https://github.com/chimple/cuba/files/15332408/logs.for.Add.subject.button.txt)

**Comment by renukaj07** [comment]
@pratapramesh  did you tested in master apk?

**Comment by pratapramesh** [comment]
@renukaj07 yes tested in master APk, if we create new profile and play any lessoncard in in different pages means the Add subject button will disappear

**Comment by pratapramesh** [comment]
Issue is still there
After creating new profile if user play any lessoncard in different page then Add Subject button will disappear


https://github.com/user-attachments/assets/d837aebf-91cb-41b7-b4c4-4babaa590377

**Comment by Pramodmarssun** [comment]
After creating new profile and playing any lesson's from diffrent screen is not making disappear the add subject button.
We can move this story to done
