### ISSUE TITLE
Avatar

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1473]
Implement the Avatar suggestions
Make sure the entire suggestions are also covered under this
The lessons played and liked from avatar needs to be updated under favourites

**Comment by Pramodmarssun** [comment]
**1. Played lessons's not updating**
**Problem:** played lesson's not coming in Played and Liked tabs

**Comment by pratapramesh** [comment]
**1. Default icon is showing in avatar**
![Screenshot_20240618_084116](https://github.com/chimple/cuba/assets/138564361/a1d5bf39-e103-49fc-8c75-88ae6d09ec46)
![Screenshot_20240618_084057](https://github.com/chimple/cuba/assets/138564361/7fddac59-9c47-4050-b378-199e1bd919b3)
![Screenshot_20240618_084039](https://github.com/chimple/cuba/assets/138564361/b49e6485-fc5d-4dc9-aad4-35a33e2acca6)
![Screenshot_20240618_083911](https://github.com/chimple/cuba/assets/138564361/0901539f-796c-4b85-b176-d85c7dbda10e)

**2. Hindi subject is showing 3 times in avatar**

https://github.com/chimple/cuba/assets/138564361/ef3a265e-0de9-4098-af9c-01f2bf2bf21f

**Comment by Pramodmarssun** [comment]
- Course image is miss matching some times 
- Multiple choice image will be delyed before displaying in lenovo tab

**Comment by pratapramesh** [comment]
Yes and No buttons are disable and not able to play any lesson card

https://github.com/chimple/cuba/assets/138564361/4133f33f-52e7-486d-bbf7-f79adae853cc
