### ISSUE TITLE
Adding/updating the results after playing the game

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1476]
This addition includes Homework as well

**Comment by Pramodmarssun** [comment]
Verified playing lessons in Subject screen and Home work screen **Played lesson data is updating in data base** 
**We have to verify in Avatar, Suggestion and offline played lessons**

**Comment by Pramodmarssun** [comment]
Once developers work on download, Avatar and suggestion screen we can test for now we will be moving it to done as Bhanu mentioned
