### ISSUE TITLE
Live Quiz

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1477]

**Comment by Pramodmarssun** [comment]
Join Quiz button kept loading, we can't join the live quiz to verify further

**Comment by Pramodmarssun** [comment]
**1. Not displaying Not played students in Joining Room
Description:** When the multiple users of same class Join the same Live quiz we are not getting any not played students profile in the Not played table.

**2. Blank screen
Description:** After joining the Live quiz once the timer completes user is getting blank screen

**Comment by Pramodmarssun** [comment]
When multiple students from same class joining same live quiz student profiles are not displayed in waiting room and in the Q/A flow till few levels, after play some lesson's all the student profiles will be displayed
