### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1478]

**Comment by Pramodmarssun** [comment]
1. **Keyboard Not Popping Up:**
**Issue:** The keyboard does not pop up when clicking on the search icon.
**Description:** Users are unable to start typing their search query immediately upon clicking the search icon as the on-screen keyboard does not appear automatically.

2. **Keyboard Overlapping Lessons:**
**Issue:** After searching for lessons, the keyboard must be closed manually, as it overlaps the lessons until closed.
**Description:** The on-screen keyboard remains open after performing a search, obstructing the view of the search results, requiring users to close it manually.

3. **Empty Screen for No Results:**
**Issue:** When no lessons are found for a search query, an empty screen is displayed.
**Description:** There is no message or indication shown to the user when a search query returns no results, leading to a blank screen without context.

4. **Arithmetic Characters Handling:**
**Issue:** Arithmetic characters in search queries do not yield math-related lessons.
**Description:** When users input arithmetic characters (e.g., +, -, *, /) in their search queries, the app does not display relevant math lessons, missing an opportunity to provide contextual search results.

 5. **Lack of Auto-Suggestions:**
**Issue:** The search functionality does not provide auto-suggestions.
**Description:** Users do not receive real-time suggestions while typing their queries, which could help them refine their search terms and find lessons more efficiently.

6. **Offline Search Inaccuracy:**
**Issue:** Search results are inaccurate when performed offline, showing only locally available data.
**Description:** In offline mode, the search functionality relies on locally stored data, which may not be comprehensive or accurate, leading to potential discrepancies in the results displayed.

7. **Character Removal and Reappearing Issue:**
**Issue:** Slow typing causes the last characters to be removed automatically, and clearing the searched text makes it reappear.
**Description:** When users type their search queries slowly, the last characters are deleted automatically. Additionally, when clearing the search text, the previously typed characters reappear, disrupting the search experience.

**Comment by Pramodmarssun** [comment]
Keyboard not popingup and character removal and reapearing issues is fixed.
Arithmetic Characters Handling and Lack of Auto-Suggestions will be not working.
Offline search inacuracy will be improving n the future.

As of above commments we can move this story to done.
