### ISSUE TITLE
Teacher mode

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1485]

**Comment by pratapramesh** [comment]
1. School name is not same in both homework page and Teacher mode
![Screenshot_20240611_203034](https://github.com/chimple/cuba/assets/138564361/5aef903f-d491-4b37-8366-5dbf55c06a53)
![Screenshot_2024_0611_194648 (1)](https://github.com/chimple/cuba/assets/138564361/c63321a0-ef71-40f0-ab2c-f0dbf4aa15f3)

2. Two profiles are showing in teacher mode
![Screenshot_2024_0611_194648 (2)](https://github.com/chimple/cuba/assets/138564361/3868d84d-9676-4ea4-8ef9-9836bd50ddbf)

3. School name allignment is not proper

**Comment by pratapramesh** [comment]
School name allignment is not proper, except that no issues
