### ISSUE TITLE
Create  'isUserExists' cloud function

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1496]

**Comment by Pramodmarssun** [comment]
1. Phone number Login not working
2. Google Login:
       -  Google Login successfully Login once 
       - Google Login not working from 2nd time onwards 


**ScreenRecord:**

https://github.com/chimple/cuba/assets/108517798/d2561078-b383-4bcd-9327-9d38a270d63a

**Comment by Pramodmarssun** [comment]
Google sing-in is working now.
We will test complete Login functionalities once we complete the #1472 story
