### ISSUE TITLE
Refactoring the Whatsapp Chatbot flow to break the loop

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1514]

**Comment by Pramodmarssun** [comment]
1. **Help Menu Issue:**
Description: The new help menu has clickable links when using WhatsApp on the web.

2. **Chapter Selection Loop Issues:**
Description 1: When in the chapter selection loop, sending any message causes the main menu to appear. Clicking on "Continue" then suggests the next two chapters to assign.
Description 2: If "More options" is selected in the chapter menu and the user sends "Hi," different chapters are displayed.

3. **Lessons Selection Loop Issues:**
Description 1: When in the lessons selection loop, sending any text results in only two lessons being available to click, with no option to change lessons.
Description 2: If "More options" is selected and text is sent, three lessons are displayed but there is no option to proceed further.
4. **Main Menu and Continue Options in Chapter Selection:**
Description: Users receive main menu and continue options in the chapter selection process.
**Steps to Reproduce:**
      1. Click on "Assign Homework."
      2. Click on "More option."
      3. Send any text, like "Hi." 
      4. Click on "Continue."
      5. Click on "More option" again.
      6. Send any text, like "Hi."
      7. Click on "Continue."

**Comment by Pramodmarssun** [comment]
Issue 1,2 and 4 is fixed.
For issue number 3 I have created #1663 

This story we can move it to done
