### ISSUE TITLE
Auto-created posters of top star performers of the week in the chatbot

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1515]

**Comment by Pramodmarssun** [comment]
1. This is how report looks in mobile 
   
![IMG-20240724-WA0007](https://github.com/user-attachments/assets/542e1d9b-2574-4aac-b920-dc3f771cd0cb)



2. We are not getting top performer report when the choosen language is Kannada. Its working when the choosen languge is Hindi and English

**Comment by Pramodmarssun** [comment]
Star performer report is not genrating

**Comment by rakshith-arch** [comment]
@Pramodmarssun can you just eloborate the issue that you are facing.

**Comment by Pramodmarssun** [comment]
When I select the top performer option, the bot does not respond. 

**Steps to reproduce:**
1. Open whatsapp 
2. select Chimple testing chatbot 
3. Send Hi and select more option 
4. select star performer option in the list given 
5. Here we can see we are not receving any response
