### ISSUE TITLE
Provision to check individual reports in chatbot

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1516]

**Comment by Pramodmarssun** [comment]
Here when we select Class wise option first and after receving report if we click on Student wise data again in the same option, we get main menu option

**Steps:**
1. In main menu select More option
2. In option Select Send Report 
3. Click on Class wise and after genrated 
4. Click on Studnet wise in the above same option where we choose Class wise 
5. Here we get Main menu
