### ISSUE TITLE
"Add Subject" functionality missing in Supabase apk

### ISSUE THREAD

**Issue by Ashish1998** [chimple/cuba#1522]
**Description**
In the subject screen the "add subject" functionality needs to be added.

**Comment by SWETHAKRISHNA2** [comment]
Description
When I click on medium of instruction drop down selected as hindi 
After that I open the subject screen page every subject name is showing on hindi language except english  name 

![Screenshot_2024-06-12-11-51-53-289](https://github.com/chimple/cuba/assets/138753773/ee671221-c735-4cf3-b885-14d737ec16c0)
![Screenshot_2024-06-12-13-47-33-926](https://github.com/chimple/cuba/assets/138753773/fc9c6599-b6f0-41ca-8a0a-7ded73f2753d)
