### ISSUE TITLE
Download Lesson's and Chapter Feature is not working 

### ISSUE THREAD

**Issue by Pramodmarssun** [chimple/cuba#1524]
**Description**
Even if we play the lesson or clicking on download button, lesson's are not downloading.

**Comment by Pramodmarssun** [comment]
1. **Download All Button Issue:**
**Issue:** Download all feature is not functioning in the Homework screen; it reloads and shows the download all button again after some time.
**Description:** Users are unable to download all chapters or lessons in the Homework screen as intended. The download process does not complete successfully and resets.

2. **Partial Download Failure:**
**Issue:** When selecting multiple chapters to download, switching screens or changing grades results in only a few chapters being successfully downloaded while others fail.
**Description:** Users experience inconsistencies in the download process where some selected chapters fail to download completely when navigating between screens or changing grades.

3. **Loading Issue on Lenovo Tab:**
**Issue:** On Lenovo tablets, the download process takes an excessively long time, even for downloading a single chapter.
**Description:** Users with Lenovo tablets experience significant delays or loading times during the download process, making it impractical to download chapters efficiently.

4. **Leaderboard Data Update Issue:**
**Issue:** Leaderboard data is not updating accurately; only data for one lesson is updated despite playing more than five lessons.
**Description:** Users' progress data is not being correctly reflected in the leaderboard. After completing multiple lessons, only data for one lesson is updated, leading to inaccurate rankings and progress tracking.

**Comment by divyahariharan2103** [comment]
Increasing the estimate to 3 from 2 as an existing bug is also fixed as part of this

**Comment by Pramodmarssun** [comment]
When we change the screen or grade when download is in progress, lesson or chapter will be keep on loading.

**Comment by Pramodmarssun** [comment]
we can move do this to done.
