### ISSUE TITLE
Blank screen issue in "Chapters page"

### ISSUE THREAD

**Issue by Ashish1998** [chimple/cuba#1537]
**Description**
In a profile if we go to subject screen and play a lesson there, and we change the grade from the chapter screen grade dropdown after playing, we get blank screen. 

Logs
[Blank screen in chapter page.txt](https://github.com/user-attachments/files/15550488/Blank.screen.in.chapter.page.txt)

**Steps to reproduce** 
1. Go to subjects screen, navigate to any lesson and play the lesson.
2. After playing click on liked or continue button.
3. Go to chapter screen and change the grade from the dropdown, you can observe the blank screen 

**Screenshot** 
![Screenshot_2024-06-04-16-29-05-874_org chimple bahama (1)](https://github.com/chimple/cuba/assets/99384703/411f53c4-f21c-467d-9126-fc8ea85a54d2)

**Comment by Pramodmarssun** [comment]
This issue is fixed. we can move it to done
