### ISSUE TITLE
Keep on loading if screen goes to sleep and reopened in lessons screen.

### ISSUE THREAD

**Issue by Ashish1998** [chimple/cuba#1539]
**Description**
In the subject screen we play a lesson and we click on liked or continue button, after this if the screen goes to sleep and if we reopen, the screen keeps on loading.

**Steps to reproduce**
1. Go to subject screen and play a lesson.
2. After playing click on liked or continue button.
3. Here put the screen to sleep mode and reopen it, then it keeps on loading in the lessons screen.

**Logs**
[keep on loading supabase.txt](https://github.com/user-attachments/files/15550846/keep.on.loading.supabase.txt)

**Screenshot**
![Screenshot_2024-06-04-17-10-46-415_org chimple bahama](https://github.com/chimple/cuba/assets/99384703/debe61cd-6769-4deb-a8d8-92d17e457f18)

**Comment by pratapramesh** [comment]
This issue is fixed, we can move to done
