### ISSUE TITLE
Each time we restart the app we can see a blank screen for some time 

### ISSUE THREAD

**Issue by Pramodmarssun** [chimple/cuba#1545]
**Description:**
Every time we open and restart the app we can see a blank screen  for a few seconds (time depends on device)

**ScreenRecord:**

https://github.com/chimple/cuba/assets/108517798/9aed2d99-06ab-46aa-bbc5-4d1494f054a8

**Comment by pratapramesh** [comment]
Issue is still there

https://github.com/chimple/cuba/assets/138564361/2bfd7b72-d3f6-4647-9d94-1d7d8fc8c7fc

Device lenovo Tab

**Comment by pratapramesh** [comment]
In Lenovo tab, we can see 2sec blank screen

**Comment by pratapramesh** [comment]
https://github.com/chimple/cuba/assets/138564361/0ea35ee6-64a5-4ef6-be98-fde4f1672df4

**Comment by pratapramesh** [comment]
https://github.com/user-attachments/assets/5858f95c-1922-4361-8144-72546086b0f4

**Comment by pratapramesh** [comment]
Will create enhancement for this task
