### ISSUE TITLE
Google sign-in failed in Supabase

### ISSUE THREAD

**Issue by Pramodmarssun** [chimple/cuba#1564]
**Issue:**
When we click on Continue with google screen will load and redirect to Login page.

**Description:**
When we click on Goolge Icon to choose account and once we select and account we will be redirected to Login screen.

**Logs:**
[Login-Failed.txt](https://github.com/user-attachments/files/15764166/Login-Failed.txt)

**Comment by divyahariharan2103** [comment]
As there was multiple login and logout this issue happened where the user was treated as a Bot, hence closing the task as it will not happen in real time
