### ISSUE TITLE
Brief Display of Broken Images on Lesson, Chapter, and Course Cards

### ISSUE THREAD

**Issue by Pramodmarssun** [chimple/cuba#1588]
**Description :**
When navigating to the screen displaying lesson cards, chapter cards, and course cards, broken images are briefly displayed before the actual images load. This issue occurs for a fraction of a second but impacts the user experience.

**Steps to Reproduce :**
1. Open the app and navigate to the screen where lesson cards, chapter cards, and course cards are displayed.
2. Observe the broken images displayed on the cards for a brief moment before the actual images load.

**Expected Behavior :**
Images should load seamlessly without displaying broken images.
Users should not notice any flickering or broken images while loading.

**Actual Behavior :**
Broken images are briefly displayed on lesson cards, chapter cards, and course cards before the actual images load.

**Screen Record :**

https://github.com/chimple/cuba/assets/108517798/d5490770-76d2-470c-8a54-ebe773381bd8

**Environment:**
Device: Lenovo Tab
OS: Android 10

**Comment by pratapramesh** [comment]
Here all icons in Avatar is too small
![Screenshot_2024-07-05-13-26-24-170](https://github.com/chimple/cuba/assets/138564361/bf3a9732-758d-4252-ab0b-950ab982f76c)
![Screenshot_2024-07-05-13-25-52-589](https://github.com/chimple/cuba/assets/138564361/ba8aeed0-4133-458e-a327-ad166b3d3236)
![Screenshot_2024-07-05-13-27-14-979](https://github.com/chimple/cuba/assets/138564361/21f288f6-4e39-4bc1-98d1-0c276d1fdd12)
![Screenshot_2024-07-05-13-30-13-645](https://github.com/chimple/cuba/assets/138564361/626f485a-e369-496f-ad9a-18737016dab0)

**Comment by pratapramesh** [comment]
No issues
