### ISSUE TITLE
Infinite loading in offline mode

### ISSUE THREAD

**Issue by pratapramesh** [chimple/cuba#1602]
**Description: Infinite loading when we open the app in offline mode**

**Steps:**
1. Install the app and login
2. Download few lessoncard
3. Turn off the internet and play few lessoncard
4. Next day open the app in offline mode

**Logs:**
[infinite loading logs.txt](https://github.com/user-attachments/files/15945020/infinite.loading.logs.txt)

**Comment by Pramodmarssun** [comment]
I have not faced any issues playing lesson's and after turning on the internet.
We can move this bug to done
