### ISSUE TITLE
Script to add school data for Supabase

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1606]
Student login using school and class id password to be as part of this task

**Comment by vinaypanduga** [comment]
https://docs.google.com/spreadsheets/d/1TcXzA_8PC12nybsRX17-scwHMO9rBwN-J3GUfr5EZh0/edit?usp=sharing

School Data format

**Comment by Pramodmarssun** [comment]
If we are creating student profile for class 1st, student will get all Grade 1 course

**Comment by Pramodmarssun** [comment]
We can move this story to done.
