### ISSUE TITLE
Create Chimple Library

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1625]

**Comment by RadhaG3** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG5uQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--972fa83f4de6e8ee402addb392b6eb839ff2cb87/image.png" alt="image.png" />

**Comment by pratapramesh** [comment]
1. In web subjects are overlapping

<img width="960" alt="SnapCrab_NoName_2024-9-24_16-26-53_No-00" src="https://github.com/user-attachments/assets/9a85821c-6ccb-4967-a362-ca08a7abeaad">

2. Button allignment issue
![Screenshot_20240924_135341](https://github.com/user-attachments/assets/1d93a275-c4b6-4d97-b064-f650d2d55f63)

3. Sometimes the dropdown colour changes to gray, but other times it stays the same
![Screenshot_20240924_140058](https://github.com/user-attachments/assets/1c1ee490-d950-4689-88f2-84922b75c002)
![Screenshot_20240924_140052](https://github.com/user-attachments/assets/6421c42a-cecb-4680-9766-76975f1c4214)

**Comment by pratapramesh** [comment]
1. When we search any lessoncard in Search page, the lessoncards are overlapping and 'Add/remove'  button is missing 

![Screenshot_20241004_111329](https://github.com/user-attachments/assets/e1a6c2a5-3867-4e03-902f-fe1347c80459)
![Screenshot_20241007_080720](https://github.com/user-attachments/assets/66d8430c-339a-43fd-954a-f7d5c42327ec)

2. Chapters allignment Issue
![Screenshot_20241004_112056](https://github.com/user-attachments/assets/52570678-40b5-4e6d-adcb-81bfe046bfbd)

3. Dropdown is closing automatically

https://github.com/user-attachments/assets/550e6853-ebb9-4e9f-8d60-b09de7907df2

**Comment by pratapramesh** [comment]
No issues
