### ISSUE TITLE
Create Class (when logged in as Principal/Coordinator)

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1626]

**Comment by RadhaG3** [comment]
**User Story**
As a Principal, I should be able to create a class. Also, I should be able to edit/delete a class.

**Acceptance Criteria**

(i) **Create Class**
 _Given That_ User navigates to Classes page
Sliders ->Manage Classes -> Classes
_When Clicked_ on 'Add'
_Then_ User to enter the class name and click create

(ii) **Edit Class**
 _Given That_ User navigates to Classes page
Sliders ->Manage Classes -> Classes
_When Clicked_ on a chosen class
_Then_ User to edit the class name and click Update

(iii) **Delete Class**
 _Given That_ User navigates to Classes page
Sliders ->Manage Classes -> Classes
_When Clicked_ on a chosen class
_Then_ User to  delete the class name and click Delete

<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVhvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--571eda41cd346187f8d4de8f42dc2d3b35ec3bb5/image.png" alt="image.png" />

**Comment by pratapramesh** [comment]
After editing the class name and clicking the Update button, the old Class name is still showing instead of new one.

**Comment by pratapramesh** [comment]
No issues
