### ISSUE TITLE
Creating flow to generate individual report in chatbot

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1631]

**Comment by Pramodmarssun** [comment]
We are not receiving individual or class-wise reports in the chatbot

**Comment by Pramodmarssun** [comment]
Still it is not working.

**Comment by Pramodmarssun** [comment]
1. For all school the Grade name is showing Ash
     
![WhatsApp Image 2024-08-08 at 2 49 38 PM](https://github.com/user-attachments/assets/b713c872-f4b0-4425-9d7e-357513435eeb)

2. If we have English G1 and English G2 in same class and if we genrate the report we are getting both, we can see English

3. Every time we select Student name to genrate report after genrating the report we are receiving Main menu. In this case we have to start complete report genrating flow to get one more student report

**Comment by Pramodmarssun** [comment]
- When we want to genrate indivisual student report for inactive student we are not getting any response from chatbot
