### ISSUE TITLE
Played Tab page issue

### ISSUE THREAD

**Issue by pratapramesh** [chimple/cuba#1653]
**Description**: in Played tab page, if i scroll the lessoncards it will refresh and load from1st lessoncard

https://github.com/user-attachments/assets/b67a5125-5025-4c80-8d28-1b9d16f284e1

Logs: 
[referesh issue logs.txt](https://github.com/user-attachments/files/16285351/referesh.issue.logs.txt)

**Comment by Pramodmarssun** [comment]
If we scroll lesson cards to last lesson it will quickly take us to latest played lesson in this case if we want to play any of last lesson's from played tab we can't play

**Comment by pratapramesh** [comment]
No issues
