### ISSUE TITLE
Broken Images on Lesson, Chapter, and Course Cards 

### ISSUE THREAD

**Issue by pratapramesh** [chimple/cuba#1673]
1. Description: lesson cards, chapter cards, and course cards, broken images are displayed before the actual images load

https://github.com/user-attachments/assets/e348577d-889c-472b-90d9-18f2f752672f

2. Default subject icon is not there for few subjects
![Screenshot_2024_0726_155419](https://github.com/user-attachments/assets/78dee058-33b2-486c-823f-a2cea67efee2)

**Comment by pratapramesh** [comment]
![Screenshot_20240805_111235](https://github.com/user-attachments/assets/b670ed98-62ad-4875-b3c7-e85b48574aec)

**Comment by pratapramesh** [comment]
No issues

**Comment by pratapramesh** [comment]
![Screenshot_20240808_213238](https://github.com/user-attachments/assets/3eced7c7-ab4b-482a-befc-ebb243482483)

**Comment by pratapramesh** [comment]
Issue is still there

**Comment by Pramodmarssun** [comment]
We can move this story to done
