### ISSUE TITLE
Class selection page

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1745]
As a Developer,
I need to create a dummy flow with the School detail and class detail and store in local storage 
So that it can be used in all the pages

**Comment by Pramodmarssun** [comment]
- we Have options to manage school and manage class and its clickable

**Comment by Pramodmarssun** [comment]
We have two options in the hamburger menu: Schools and Classes. Both options are clickable. Clicking on either option will navigate you to the corresponding section you selected.
we can move this to done
