### ISSUE TITLE
Displaying wrong chapter name in WhatsApp chatbot

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1747]
Issue:

During the assignment of lessons using the WhatsApp chatbot , it is seen that user selects a Chapter during the process of assignment but in the assignment confirmation summary message a different chapter name is displayed

This is happening because same lesson belongs to multiple chapter and hence in assignment confirmation message we are getting different chapter name

**Comment by Pramodmarssun** [comment]
This is working, we can move this story to done
