### ISSUE TITLE
View Student Progress

### ISSUE THREAD

**Issue by talapadi** [chimple/cuba#1759]

**Comment by RadhaG3** [comment]
<img width="250" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGJjQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eef57a387b65e4faf8375faa422af1684a5ccc45/image.png" alt="image.png" />

**Comment by pratapramesh** [comment]
- Here i played 12 lessoncards but in report page it's showing the count is 9

https://github.com/user-attachments/assets/436ee951-c0ea-4fc7-9eba-b9ec227af3f2

- In web 'to'  date range is not showing properly
<img width="960" alt="SnapCrab_NoName_2024-12-5_9-36-26_No-00" src="https://github.com/user-attachments/assets/8e6d4036-6b7a-449e-a890-705db5628ed0">

- Allignment of icons are not proper
![Screenshot_20241204_203822](https://github.com/user-attachments/assets/0552be33-4e5b-4e67-9128-7876e0509c34)

- When I selected a date range  and navigate to the student progress page, then returned to the previous page, the date range I had selected was changed and i selected 'All activities' changed to "Assignments only'

https://github.com/user-attachments/assets/43ec682f-2735-4b96-a5c8-ac866c06cbc9

**Comment by pratapramesh** [comment]
No issues
