### ISSUE TITLE
Class selection/ School selection

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1761]
Display all schools for the user. After selecting a school, show all the classes associated with that particular school after selecting the class it should navigate to home page. The selected school and class should be stored for easy access across all pages.
Example: Similar to how we access student in Cuba.

**Comment by Pramodmarssun** [comment]
1. Here Once we click on School Mode we get a option's to choose schools user is part of, next we get class to choose then we redirect to home page
**But we are not sure we are in choosen class becasue we are showing anywhere the choosen class right now**
