### ISSUE TITLE
Time exceeded notification pop up

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1767]
As a Student,
Whenever I exceed the give time for a day by using the app,
I should get a alert notification pop saying that " "

Therefore set the maximum app usage limit for the child and when the child exceeds the time send a notification pop.

**Comment by pratapramesh** [comment]
![Screenshot_2024-10-29-15-10-14-205](https://github.com/user-attachments/assets/17960e0e-ad88-4cc8-94b7-38d8f21db95f)

**Comment by pratapramesh** [comment]
1. Still receiving the Popup when app is running in the background
2. Allignment issue is still there
3. instead of continue button if user click somewhere in the screen then popup will disappear
