### ISSUE TITLE
Getting 'Main menu' message when we select 'Remind students' option

### ISSUE THREAD

**Issue by pratapramesh** [chimple/cuba#1771]
**Descripton**: When we are using chatbot in Kannada/Hindi language, if we select 'Remind students' option will get Main menu message 

![Screenshot_2024_0916_122853](https://github.com/user-attachments/assets/d3450666-78a3-45dd-b12d-93f9d55984b3)
![Screenshot_2024_0916_123049](https://github.com/user-attachments/assets/942a2abf-8e4e-43ea-a7b0-37cb569d5774)

**Comment by Pramodmarssun** [comment]
We can move this to done
