### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#181]

**Comment by Pramodmarssun** [comment]
1. When we select the mobile field to enter a mobile number once the keypad 
    comes up, we can't see the mobile number
2. In the Lenovo tab mobile number box borderline is not  completely visible  
![Screenshot_20230413_150315_Chimple](https://user-images.githubusercontent.com/108517798/231720700-3d8625a6-2f4b-4b2c-84b1-63b9576cfe82.jpg)
![Screenshot_2023-04-13-15-05-35-600](https://user-images.githubusercontent.com/108517798/231720707-25e62861-64b3-4a3a-bbc0-fa7bdef68242.jpeg)
![Screenshot_2023-04-13-15-01-25-491](https://user-images.githubusercontent.com/108517798/231720713-92104ebf-3809-433d-b694-a8149f0748aa.jpeg)

**Comment by Pramodmarssun** [comment]
![Screenshot_20230424_102309_Chimple](https://user-images.githubusercontent.com/108517798/233918299-2f588162-65c5-4ecb-804b-5b1bf4eb4c23.jpg)

**Comment by Pramodmarssun** [comment]
1. Login screen sentences became overlapping with the background color
2. Mobile field is moving middle to the left of the screen and It looks small on the screen 

![Screenshot_20230426_104703_Chimple](https://user-images.githubusercontent.com/108517798/234476424-cbf45d08-6bdc-4d26-9643-6f6fcc8bc67f.jpg)
![Screenshot_20230426_104708_Chimple](https://user-images.githubusercontent.com/108517798/234476428-2ed7dec4-ba63-464e-8682-165b26cbcff5.jpg)
