### ISSUE TITLE
Authentication by phone number

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#182]

**Comment by Pramodmarssun** [comment]
- [ ] When we enter phone number and click on login, automatically we will exit from the app

**Comment by Ashish1998** [comment]
- Every time we login with phone number it asks parent name.
- When we login with phone number and create a profile, it keeps loading at the home screen. (It happens even when we try to open previously created profile)
- In the OTP text field and Parent name text field if we enter the text and close the key board the letters which we have entered will be erased.

**Comment by Ashish1998** [comment]
![Screenshot_2023-07-11-15-47-29-643](https://github.com/chimple/cuba/assets/99384703/1394dec7-f3ff-419c-83e6-f4e59f742241)

**Comment by Pramodmarssun** [comment]
Here when we try 1st OTP, it will say it's invalid
