### ISSUE TITLE
Implementation of  phone number recommendation and OTP auto-detection during login

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1821]

**Comment by pratapramesh** [comment]
1. I'm getting an error message when I try to log in using the autofilled phone number.

https://github.com/user-attachments/assets/32d3ac8f-5916-4c52-bc4c-1a66413a451c

2. keep on loading issue when i signout and sign back in

https://github.com/user-attachments/assets/a9c3b736-cf10-4389-a32e-f6074c8c3242

3. Allignment issue
![Screenshot_20241104_091000](https://github.com/user-attachments/assets/1c3b599a-e49d-4d8a-b1b9-3491457c870a)

**Comment by pratapramesh** [comment]
No issues
