### ISSUE TITLE
Show the lessons completed by the user

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#197]

**Comment by talapadi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-60919d7cc7088b000e0264d0/issues/chimple/cuba/197?planning-poker) with Zenhub @talapadi @bhanugummana @Mary-Harshitha @Pramodmarssun @Sutara-Skanda

**Comment by Pramodmarssun** [comment]
![Screenshot_2023-05-04-12-20-45-861](https://user-images.githubusercontent.com/108517798/236376072-6e13b7b5-d8e1-4d3e-87bb-4138839948b4.jpeg)
