### ISSUE TITLE
Parent screen with tabs

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#202]
Add following tabs:

- update login info
- display or add profile
- settings [such as : language and sound]
- Help/contact

**Comment by Pramodmarssun** [comment]
1. Parent button is not having a lock
2. Sometimes parent headers button not working when we click on them

![Screenshot_20230426_111211_Chimple](https://user-images.githubusercontent.com/108517798/234480376-4b6fb409-ac1b-42be-87c8-bdf6cd1a8b28.jpg)
