### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#232]
- [ ] 1. Signup
- [ ] 2. Login
- [ ] 3. Update user profile
- [ ] 4. logout
- [ ] 5. forget password

**Comment by Ashish1998** [comment]
In Malta if we click on "continue with Google" the screen keeps loading and lands on the same login page. If we kill the app and open it again then it will directly login.

https://user-images.githubusercontent.com/99384703/234505987-3dd101e8-d3e4-48ca-87ad-8eee6d30deb9.mp4

**Comment by Ashish1998** [comment]
In Malta, if we click on login with phone number or create account with phone number it automatically sets the country code to Afghanistan.


https://user-images.githubusercontent.com/99384703/234507624-c19dc3d8-14d4-47bd-b079-76273d9d7635.mp4
