### ISSUE TITLE
Language of parent/user - select when creating account

### ISSUE THREAD

**Issue by talapadi** [chimple/cuba#248]

**Comment by Pramodmarssun** [comment]
1. **Select App Language** is overlapping with background color
2. language drop-down button coming in the middle 
![Screenshot_20230426_104132_Chimple](https://user-images.githubusercontent.com/108517798/234475672-1138b65e-3549-496b-8cd6-ce4a2805ed80.jpg)
![Screenshot_20230426_103718_Chimple](https://user-images.githubusercontent.com/108517798/234475674-fe48e2e8-3951-43f3-9b32-d615018a712a.jpg)
