### ISSUE TITLE
Loved/History

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#267]

**Comment by Pramodmarssun** [comment]
We have tested and still need more testing

**Comment by Pramodmarssun** [comment]
When we switch between fav to history or history to fav, we can see only some words written on lesson card


https://github.com/chimple/cuba/assets/108517798/06c01d0a-7b7e-46e3-9370-088af0d519c4

**Comment by Pramodmarssun** [comment]
Android version-11
RAM 2GB
