### ISSUE TITLE
Lock for parental screen 

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#276]

**Comment by Pramodmarssun** [comment]
![Screenshot_2023-05-04-12-32-56-614](https://user-images.githubusercontent.com/108517798/236375714-58c67da2-4721-4651-8e5a-ec612f6f54d1.jpeg)
![Screenshot_20230505_093031_Chimple](https://user-images.githubusercontent.com/108517798/236375718-9a12bc3a-a98a-4cb2-8b15-1ca0738ebb0b.jpg)
