### ISSUE TITLE
UI Enhancements

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#280]
1. Set minimum size for buttons/tabs
2. Set minimum font size
3. Set the dropdown size uniformly
4. Login page text box allignment

**Comment by Pramodmarssun** [comment]
1. Text font size is displaying small on mobile devices 
2. buttons will get smaller when we open the keyboard on mobile devices
3. Drop-down alignment is not coming same in all drop-down button 

https://github.com/chimple/cuba/assets/108517798/c8981b2c-ac66-4783-8d38-26ef0ec53144

![Screenshot_2023-05-11-13-16-33-78_c3308f5fd3310a813b9c5e58eb423f68](https://github.com/chimple/cuba/assets/108517798/84d26eee-9e7c-43b9-832e-7efb7d773205)
