### ISSUE TITLE
Improvements for parental lock

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#293]

**Comment by Ashish1998** [comment]
- In web swiping is not working.
- UI is not matching with mockup.

![Screenshot_2023-06-30-15-04-33-126](https://github.com/chimple/cuba/assets/99384703/6a2c6756-8ba6-421d-8d13-6a7485479e90)
![Screenshot_2023-06-30-15-00-43-68_c3308f5fd3310a813b9c5e58eb423f68 (1)](https://github.com/chimple/cuba/assets/99384703/88a4afa7-9a2d-475f-a224-a82045d7f487)
