### ISSUE TITLE
When we are completing creating profile, screen will be keep on loading

### ISSUE THREAD

**Issue by Pramodmarssun** [chimple/cuba#299]
![Screenshot_2023-05-08-09-54-01-234.jpeg](https://images.zenhubusercontent.com/642127a210a9a917cad59e05/1a888dc3-a359-4bdb-8ccd-01d7e1d3aff2)

09:43:31.544  E  File: http://localhost/static/js/main.86fd0489.js - Line 2 - Msg: Uncaught (in promise) FirebaseError: No document to update: projects/cuba-stage/databases/(default)/documents/User/JkLEgu8PhOumcgbVG6UH

**Comment by Ashish1998** [comment]
Here when we use same gmail ID for both cuba and malta we are facing this issue.
