### ISSUE TITLE
Fix the text field when the Keyboard pops-up

### ISSUE THREAD

**Issue by Pramodmarssun** [chimple/cuba#318]
-Screens:
- [x] Phone Number
- [ ] Enter the OTP
- [ ] Enter the Parent’s Name
- [x] Enter the Child’s Name
- [x] Search (Already Top on the screen)
- [x] Enter the class code in home work screen

**Comment by Pramodmarssun** [comment]
Here when the text box's and texts will move when the keyboard is opened along with that **Next** button is also disappearing from the screen

**Comment by Ashish1998** [comment]
In some devices text field is scrollable.
