### ISSUE TITLE
Drop-Down Issue

### ISSUE THREAD

**Issue by Pramodmarssun** [chimple/cuba#319]
This is the mockup 

![image (2)](https://github.com/chimple/cuba/assets/108517798/835cc9fa-b6ed-435c-9252-72c81269caad)

**Issues**
 

- [ ] Text on the drop-down is coming on the left side or right side 

![Screenshot_2023-05-17-14-17-59-46_c3308f5fd3310a813b9c5e58eb423f68 (1)](https://github.com/chimple/cuba/assets/108517798/25f980ea-4578-4888-999e-b9bb0fbab829)

- [ ] Drop-Down is not coming in the middle, sometimes it is coming top of the drop-down or left side or right side

![Screenshot_20230517_142135_Chimple (1)](https://github.com/chimple/cuba/assets/108517798/c15abb83-8cd4-4813-96e9-dfb26b8f15bd)

- [ ] Lines and Border and color of selected option are not matching the mockup

- [ ] If drop-down options are more it should be able to scroll

**Comment by Ashish1998** [comment]
![Screenshot_20230605_131157_Chimple](https://github.com/chimple/cuba/assets/99384703/287d5658-2ab8-45cc-8d44-35df44a7fd87)
