### ISSUE TITLE
Parent screen and Progress headers are not matching mockup

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#375]

**Comment by Ashish1998** [comment]
![Screenshot_20230606_154351_Chimple](https://github.com/chimple/cuba/assets/99384703/9823fc7f-4241-4af1-8e40-9ac63220a2d3)

![Screenshot_20230606_154415_Chimple](https://github.com/chimple/cuba/assets/99384703/773c7f08-3d0f-48f0-b74e-86bc8e0fdee5)

**Comment by Pramodmarssun** [comment]
- When we go to see the progress in student progress screen, we can click on different subject but 
   data will be the same (We don't get to see if we have played lessons in  the other subjects also)
- If the app goes to sleep in progress screen, when we reopen the app we can see empty screen

![Screenshot_20230606_161249_Chimple](https://github.com/chimple/cuba/assets/108517798/87874f06-6e11-4a79-a104-c541a7bb9e62)

-

**Comment by Ashish1998** [comment]
![Screenshot_2023-06-12-11-18-38-28_c3308f5fd3310a813b9c5e58eb423f68](https://github.com/chimple/cuba/assets/99384703/2b9823c3-151e-42fe-bce8-c7dd273ce3e1)

**Comment by Pramodmarssun** [comment]
Now it's ok
