### ISSUE TITLE
Medium of Instruction texts is not complete in the dropdown. It's showing dots because of more characters  

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#437]

**Comment by Ashish1998** [comment]
- Still in some devices the text is not visible properly.
**MI phone -**
![Screenshot_2023-06-19-11-11-02-168_org chimple cuba](https://github.com/chimple/cuba/assets/99384703/ff3a117d-d382-45d3-9a85-6da38328619d)

**Oneplus -**

![Screenshot_2023-06-19-11-09-07-46_c3308f5fd3310a813b9c5e58eb423f68](https://github.com/chimple/cuba/assets/99384703/446f0b02-9a31-424f-99d1-563e7eba3e92)

**Comment by Pramodmarssun** [comment]
In one of the device still issue is coming
