### ISSUE TITLE
Show the Loved icon on the lesson card

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#461]

**Comment by Ashish1998** [comment]
- Here after playing the lesson if we like the lesson the the loved icon will not be displayed on the lesson card, we need to switch the screen and if we return to the lesson card screen then it will be displayed.

**Comment by Pramodmarssun** [comment]
Loved icons are coming on the lesson cards after liking the lesson
But it's not reflecting quickly so @RamReddyGowra is working on issue #514 and this fix this issue also so I am moving this to done
