### ISSUE TITLE
In progress report screen it is only showing digital skills progress.

### ISSUE THREAD

**Issue by Ashish1998** [chimple/cuba#476]
![Screenshot_2023-06-20-16-30-07-710.jpeg](https://images.zenhubusercontent.com/6423d12de632a60d8c53681e/42bb109a-bb79-45aa-bd44-34cc31db9574)

**Comment by Pramodmarssun** [comment]
1. The results are not showing quickly, it's taking some time to display 
2. Some time automatically progress will get change
