### ISSUE TITLE
After lesson completion getting home page-search bar

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#500]

**Comment by Pramodmarssun** [comment]
- [ ] When we play and Like the lesson or click on continue playing button keyboard will pop-up and it will close automatically in less than sec
- [ ] If we exit form the lesson also key board will pop for less than sec


@akshattak when the device will go to sleep when they are in the search screen what should happen when they turn on?

**Comment by Ashish1998** [comment]
All the 3 issues is still happening.
