### ISSUE TITLE
Parent language issue

### ISSUE THREAD

**Issue by Pramodmarssun** [chimple/cuba#508]
- select your language screen
   Here when we change english to hindi, some time text will not change english to hindi

- If we select language as Hindi and login and click on Profile which is in english and sign out, Parent language will change to   English but in drop-down it will be showing Hindi

**Comment by Ashish1998** [comment]
Issue still happening.
![Screenshot_2023-07-07-12-16-49-63_c3308f5fd3310a813b9c5e58eb423f68 (1)](https://github.com/chimple/cuba/assets/99384703/9e842ba5-b471-4449-8049-0eb7af0bde8e)
![Screenshot_2023-07-07-12-15-46-18_c3308f5fd3310a813b9c5e58eb423f68](https://github.com/chimple/cuba/assets/99384703/656b46b6-e2a2-42e0-adee-29322bb3e2ab)
