### ISSUE TITLE
Add new score card

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#510]

**Comment by Pramodmarssun** [comment]
- Here we can see **string** written on score card
- Stars not coming even after giving correct answer in all levels 
- When we click on like or continue playing lesson, we will get white screen and after sometime we will go to other screen


![Screenshot_20230717_162611_Chimple](https://github.com/chimple/cuba/assets/108517798/05b6fa54-1726-4eb7-a55e-409f70ff1e80)

**Comment by Pramodmarssun** [comment]
**When we click on like or continue playing lesson, we will get white screen and after sometime we will go to other screen**  this issue is still there

**Comment by Ashish1998** [comment]
The above issue is still happening.

**Comment by Ashish1998** [comment]
Its working.
