### ISSUE TITLE
If login profile doesn't exist then redirect to "create student login"

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#559]

**Comment by Ashish1998** [comment]
- Here if we delete the parent account and we login again, then after logging in we will go to enter child name screen, here the name of the old profile which we had will be already present in the text field. 
- And along with the name all the other info of the last profile will be present,

**Comment by Ashish1998** [comment]
- Here sometimes if we delete the exsisting profile and we login again, then after logging in we will go to enter child name screen, here the name of the old profile which we had will be already present in the text field. 
- And along with the name all the other info of the last profile will be present.
- If we try to complete the process of profile completion then it keeps on loading.
