### ISSUE TITLE
When we click on lesson, sometimes it's showing Something went wrong

### ISSUE THREAD

**Issue by Pramodmarssun** [chimple/cuba#579]
- When we click on few lesson, It's showing something went wrong and if we refresh the page and open, It will work

**Comment by talapadi** [comment]
Let us create a Remote Config for array of URLs.
If the primary is unavailable, download from secondary

**Comment by Pramodmarssun** [comment]
@pratapramesh and Swetha tested and not getting this issue's again so we moving it to done
