### ISSUE TITLE
"G" icon is not completely visible in login screen in some devices.

### ISSUE THREAD

**Issue by Ashish1998** [chimple/cuba#596]
![Screenshot_2023-07-11-11-21-19-01_c3308f5fd3310a813b9c5e58eb423f68.jpg](https://images.zenhubusercontent.com/6423d12de632a60d8c53681e/fdc56e5c-c3ea-4c21-9e12-8cc6fcb7ce68)

**Comment by Pramodmarssun** [comment]
Still happening



![Screenshot_20230717_164004_Chimple](https://github.com/chimple/cuba/assets/108517798/78111e37-307a-49fa-bc28-73d533d36cfc)

**Comment by Ashish1998** [comment]
Issue is fixed.
