### ISSUE TITLE
Popup into an animation and speak when clicked on avatar

### ISSUE THREAD

**Issue by talapadi** [chimple/cuba#609]

**Comment by akshattak** [comment]
When you click on the animation, it should animate with the speaking animation

**Comment by akshattak** [comment]
Add the animation duration based on the audio length

**Comment by akshattak** [comment]
Add the animation duration based on the audio length

**Comment by akshattak** [comment]
Add the animation duration based on the audio length

**Comment by pratapramesh** [comment]
- While playing the audio if we go to sleep mode, still audio is playing and if app is running in backgroung still we here the audio

-  Here if we click on speaker button, it's taking 2 sec delay to paly the audio

https://github.com/chimple/cuba/assets/138564361/cc356c26-3e3d-409e-a874-a995f5d178b8
