### ISSUE TITLE
Show options for user to select and on click go to particular screen

### ISSUE THREAD

**Issue by talapadi** [chimple/cuba#610]

**Comment by Ashish1998** [comment]
Issues in selecting options in Avatar screen:

- If we keep on tapping on the "start" button we will get blank screen.
- After we click on "start" button it takes 3 seconds to switch to next option even in high end device.
- If we keep on clicking "No" and at the end if we click "yes" and "no" frequently it gives us blank screen.
- After entering into any subject if we click "no" it will not take us to any other suggestion, we have to click "yes".

**Comment by pratapramesh** [comment]
- In all subjects it showing only english chapters & lessons

- If i click continuously NO in any subject , at the the end if i click on Yes or No button nothing will happen (in Do you want to paly chapter ? page )


https://github.com/chimple/cuba/assets/138564361/e807664a-8bc2-4265-a412-4870e0c6a3c7
