### ISSUE TITLE
Decide which dialogue and choices to show to the user

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#614]

**Comment by akshattak** [comment]
It will be done today

**Comment by Pramodmarssun** [comment]
- For new user we are getting **do you want play assessment?** but we don't know for which subject this belongs to.
- same choices and dialogue box is reflecting in all profiles even when we try to do deferent
- When we get 4 option's to select green color will come for all the selected options
- Some times color will not come only 
-  sometimes chimple logo will be overlapping the dialogue box

**Comment by Ashish1998** [comment]
If we keep on clicking on "Yes" button we will not be able to play that particular lesson same chapter will be displaying after few seconds the next lesson will be displayed.
 

https://github.com/chimple/cuba/assets/99384703/150f03e7-4032-434e-89e5-dd28c311b50a

**Comment by pratapramesh** [comment]
- [ ] If we click on Yes/No button the Colours are not showing like Green or Red

- [ ] The "shape tractor" chapter have 5 lesson card (shape sequence, shapes series, shape pattern, shape order, succession in shapes). If i click "No" for 6th time, it will show next chapter lesson card ( "Draw shape" chapter--> 'ballon' lesson card)

https://github.com/chimple/cuba/assets/138564361/2d79c018-c8ec-4771-8baf-17873e14b4a7

- [ ] if i switch the page/ Go to sleep mode and come back the the lesson cards are changing automatically

https://github.com/chimple/cuba/assets/138564361/378fd8fc-540c-4689-811b-c4f12edc708d

- [ ] If i click "yes" option to play 'Assessment lesson card' , first it will display next popup then it will play the 'Assessment lesson card'

https://github.com/chimple/cuba/assets/138564361/f7c70a73-a149-412d-8cd2-8cd452f784dc

**Comment by Ashish1998** [comment]
I have created a separate issue for the above mentioned bugs. (1159, 1179)
so this task can be closed.
