### ISSUE TITLE
Issue when you click on back button on OTP page 

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#641]
when you click on back button on OTP page then you enter correct or new number the timer is not started and the previously occurred seconds continued in the OTP page

**Comment by Pramodmarssun** [comment]
We can test this issue once Phone number authentication issue is fixed

**Comment by Pramodmarssun** [comment]
This issue is still happening

**Comment by Pramodmarssun** [comment]
When we click on back button from OTP screen and enter new number and click on OTP, we are able to see the seconds from 60 sec
It's working and I moving it  to done
