### ISSUE TITLE
When install chimple first time we don't see any chapters 

### ISSUE THREAD

**Issue by Pramodmarssun** [chimple/cuba#643]
When we install Chimple first time and if we click on subjects we will see the blank screen, we have to switch screen and after few seconds we can see the chapters.
If we don't switch the page, it will remain blank screen
Some times randomly also it will happens 

![Screenshot_20230719_132317_Chimple.jpg](https://images.zenhubusercontent.com/642127a210a9a917cad59e05/4da52c3f-6952-4903-9052-da32f0ea8230)

**Comment by Ashish1998** [comment]
Fixed.
