### ISSUE TITLE
When we play lesson and come back to chapter screen English text will move to right side and Drop-Down will disappear 

### ISSUE THREAD

**Issue by Pramodmarssun** [chimple/cuba#644]
Once we play the lesson and click on back button, we can see English text will move to right side of the screen

 ![Screenshot_20230719_161548_Chimple.jpg](https://images.zenhubusercontent.com/642127a210a9a917cad59e05/4e5599df-0df6-48e5-9871-7841a0bea31b)

**Comment by Ashish1998** [comment]
This issue is fixed.
