### ISSUE TITLE
If we click phone back button the profile changes from parent to teacher mode.

### ISSUE THREAD

**Issue by Ashish1998** [chimple/cuba#673]
- After login when we select as teacher mode and while selecting school if we click on phone back button it takes us to profile present in parent mode.
- And in that profile homework tab will not be present.

**Comment by Ashish1998** [comment]
- Here first time when we install the app and select teacher mode and if we click phone back button without selecting any school we will get blank screen.

https://github.com/chimple/cuba/assets/99384703/5488a534-b12e-46fd-ab2e-cb50b65ced7b

**Comment by Pramodmarssun** [comment]
This issue is still happening 

**Step's**
1. when you have Parent and Teacher options to choose select Teacher
2. select school and click on android back button
3. Here will get blank screen

**Comment by Ashish1998** [comment]
Issue was still happening in phone number login.

**Comment by pratapramesh** [comment]
It is working
