### ISSUE TITLE
Background color issue.

### ISSUE THREAD

**Issue by Ashish1998** [chimple/cuba#685]
Here in some screens blue colour is appearing in the background.

![Screenshot_2023-07-25-13-28-49-06_c3308f5fd3310a813b9c5e58eb423f68.jpg](https://images.zenhubusercontent.com/6423d12de632a60d8c53681e/c052e748-3cf9-4670-9ec0-2eed4fa9cb7a)![Screenshot_2023-07-25-17-12-44-37_c3308f5fd3310a813b9c5e58eb423f68.jpg](https://images.zenhubusercontent.com/6423d12de632a60d8c53681e/481135dc-11c4-4fa8-81be-99062dc2380c)
![Screenshot_2023-07-25-14-43-15-16_c3308f5fd3310a813b9c5e58eb423f68.jpg](https://images.zenhubusercontent.com/6423d12de632a60d8c53681e/5b7d49bc-4c6d-4c4c-8146-8b40a1689e99)

**Comment by Pramodmarssun** [comment]
It's working now in the master branch and I am moving this to done
