### ISSUE TITLE
Limit the profile name based on width in all pages

### ISSUE THREAD

**Issue by Pramodmarssun** [chimple/cuba#694]
Updated description: Not only leaderboard, Limit the profile name based on width in all pages.

In the leaderboard if student name is too long, it will display middle name not from starting

![Screenshot_20230726_163300_Chimple.jpg](https://images.zenhubusercontent.com/642127a210a9a917cad59e05/36814bb9-2d48-4e79-b068-3c26d07a59d2)

**Comment by Ashish1998** [comment]
Issue still happening.
