### ISSUE TITLE
Whenever we go to Home screen we will not get to see the lesson's, we will not see lesson's in-between loading

### ISSUE THREAD

**Issue by Pramodmarssun** [chimple/cuba#757]
- When we open the chimple we can see empty screen then loading.
- Whenever we go to the home screen from any screen we are getting this issue.

https://drive.google.com/file/d/1ULu_kzdCgtgNgxMFgMqGfyLTeX1d-wh1/view?usp=drive_link

**Comment by Ashish1998** [comment]
It is fixed.
