### ISSUE TITLE
we can paste text's in mobile number field 

### ISSUE THREAD

**Issue by Pramodmarssun** [chimple/cuba#762]
- [ ] If we copy and paste the text to Phone number field it's taking 
- [ ] If alphabets are 10, send OTP button will be enabled 

![Screenshot_20230808_181611_Chimple.jpg](https://images.zenhubusercontent.com/642127a210a9a917cad59e05/fbcf30b0-8244-4e30-87fc-9b4a4f6daaf0)

**Comment by Ashish1998** [comment]
The issue is fixed.
