### ISSUE TITLE
Update Grade and Board drop down when creating profile

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#792]
Under Board add the following:
"State board" 
"others"

Under Grade drop down add the following:
"Below Grade 1"
"Grade 1"
"Grade 2"
"Grade 3"
"Above Grade 3"

**Comment by Pramodmarssun** [comment]
After adding more option's in drop-down, still drop-downs are coming up
![Screenshot_20230817_160751_Chimple](https://github.com/chimple/cuba/assets/108517798/585c6473-7607-469c-8cf1-9e6ad443c6b5)
