### ISSUE TITLE
Language dropdown displayed before the language is displayed and also able to select the language

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#797]

**Comment by Ashish1998** [comment]
Here after installing the app, first time when we open first we will be taken to login screen then the loading appears and we will be taken to language selection screen.

**Comment by Pramodmarssun** [comment]
Before displaying app language drop-down, it's loading almost 10sec

Device : Lenovo Tab
Android : Version 9

**Comment by SWETHAKRISHNA2** [comment]
Before displaying  choose your language page , It is loading almost 4.45 sec .

Device : Tab -7305F

**Comment by Pramodmarssun** [comment]
We can close this issue. issue #961 is will fix the loading issue
