### ISSUE TITLE
Slowness in loading the home page under different network speed

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#799]

**Comment by pratapramesh** [comment]
**It's taking 1minutes 52 sec to load home page
profile page is also taking too much time
It's happening in one profile (played 1200 lesson card)**

https://github.com/chimple/cuba/assets/138564361/94589bfb-4581-4417-a5d4-3ec61c2a8ab8

**Comment by pratapramesh** [comment]
In 2G speed If i click on Liked/Played button, its taking arround 20 seconds to load the lesson cards

https://github.com/chimple/cuba/assets/138564361/4ded3f94-1835-46b5-86cf-2d48a86c5fde

Device: Lenovo tab
