### ISSUE TITLE
Add an user friendly error message for default phone number errors from fire base 

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#827]

**Comment by Pramodmarssun** [comment]
![Screenshot_20231201_153834_Chimple](https://github.com/chimple/cuba/assets/108517798/7c522a57-239c-408d-abb6-6935a065b6fe)
![Screenshot_20231204_094213_Chimple](https://github.com/chimple/cuba/assets/108517798/e5969d78-f104-4816-bf7c-dfb7e9e8ae4d)
![Screenshot_20231201_153819_Chimple](https://github.com/chimple/cuba/assets/108517798/5aad797d-8242-4436-9a4f-d83af7830c1c)
