### ISSUE TITLE
Chimple upgrade introduction screen

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#842]

**Comment by Pramodmarssun** [comment]
1. Every time user sign-out from Chimple app introduction screen will display
2. We are not able to swipe from left to right or right to left 
3. We are not having back button if the user want's know about previous introduction image
4. Content's and images are not user friendly (all languages)


 
![Screenshot_2023-10-05-14-14-19-257](https://github.com/chimple/cuba/assets/108517798/b82d7e92-e56e-4653-bd80-ce3ea12e73d6)


![Screenshot_2023-10-05-14-14-30-510](https://github.com/chimple/cuba/assets/108517798/65e427af-9ec2-43de-8539-04b396131ca6)


![Screenshot_2023-10-05-14-14-37-080](https://github.com/chimple/cuba/assets/108517798/702843a5-3560-4ef0-bf2a-db5aa4551d39)

**Comment by Ashish1998** [comment]
1. In the new texts in intro screens, there are some alignment issue in Hindi and Kannada texts. Here the texts are overlapping with the 3 dots at the bottom and some texts are over lapping on each other also.
![Screenshot_2023-10-10-12-04-17-28_ddc0fec0f25cadbb53407d57e5100bc9](https://github.com/chimple/cuba/assets/99384703/de139c50-b014-4f5b-b548-41332f0f97fc)
![Screenshot_2023-10-10-12-03-21-81_ddc0fec0f25cadbb53407d57e5100bc9](https://github.com/chimple/cuba/assets/99384703/f07e9c4c-d425-442b-bcdd-2a8151e79710)
![Screenshot_2023-10-10-12-03-14-08_ddc0fec0f25cadbb53407d57e5100bc9](https://github.com/chimple/cuba/assets/99384703/cc2c700f-b5d9-4693-8a80-fa5817b659d1)

2. Even the texts are in different positions in different devices.
-  One Plus Nord 2t
![Screenshot_2023-10-10-12-52-34-71_ddc0fec0f25cadbb53407d57e5100bc9](https://github.com/chimple/cuba/assets/99384703/e6c27e07-4f05-4c9b-b51a-1b4b1a3aca05)

- Lenovo tab
![Screenshot_2023-10-10-12-53-02-764](https://github.com/chimple/cuba/assets/99384703/677f2e43-4756-47d7-9ec2-1295081026d8)
