### ISSUE TITLE
Every time we switch user we are taken to Parent or Teacher mode selection screen.

### ISSUE THREAD

**Issue by Ashish1998** [chimple/cuba#844]
After we sign out from the profile by clicking on "switch user" we will be taken to Parent or Teacher mode selection screen but not to profile selection screen.

https://github.com/chimple/cuba/assets/99384703/10b81886-a9d4-4cf8-b93d-527204144ea5

**Comment by Pramodmarssun** [comment]
We are not getting the selecting Parent or Teacher mode page.

Step's
1. Make sure you're having teacher account in Teacher app and Parent account in chimple app
2. Install chimple or sign-out from existing chimple app
3. Click on login 
4. Here we are not getting the selection page, it will directly take us in to the student profile screen

**Comment by SWETHAKRISHNA2** [comment]
1. When I click the switch profile and it is taking to me child profile page. 
2. Issue is clear
