### ISSUE TITLE
We can able to enter Special characters in Phone number , OTP, home work text field

### ISSUE THREAD

**Issue by pratapramesh** [chimple/cuba#857]
**1. We can able to enter Special characters in Phone number , OTP, home work text field
   2. We can enter more than 6 numbers in home work text field**
   
![Screenshot_2023-09-01-15-31-55-206](https://github.com/chimple/cuba/assets/138564361/a375e735-d5dd-45d4-9217-b2a407e99e62)
![Screenshot_2023-09-01-15-31-14-485](https://github.com/chimple/cuba/assets/138564361/6977952b-9bba-4750-abad-2eb3e229c1b3)
![Screenshot_2023-09-01-15-19-38-030](https://github.com/chimple/cuba/assets/138564361/77761b21-ef83-4511-9388-2069b56b0621)

**Comment by SWETHAKRISHNA2** [comment]
still issue is there 

 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazlwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--371fe37b157357c1f92506bd942ea186a6af98e6/IMG-20230905-WA0018.jpeg)


[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEZwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--751a32db351c693d8bfe83f72516dede9cc79d88/IMG-20230905-WA0022.jpeg)
