### ISSUE TITLE
Drop-Down issue's 

### ISSUE THREAD

**Issue by Pramodmarssun** [chimple/cuba#886]
Text alignment on the drop-down is not in the middle 

![Screenshot_2023-09-11-16-48-33-91_ddc0fec0f25cadbb53407d57e5100bc9](https://github.com/chimple/cuba/assets/108517798/0eacdcf2-60c5-4539-9850-5c3014aa4cf8)

**Comment by Pramodmarssun** [comment]
Drop-Down text's are moving right side 

Device: Samsung S23
Android 13

![Screenshot_20230920_140218_Chimple](https://github.com/chimple/cuba/assets/108517798/74d53f57-135d-4e78-b946-408cde9882ab)

**Comment by pratapramesh** [comment]
No issues
