### ISSUE TITLE
Alignment of liked icon on lesson card is not proper.

### ISSUE THREAD

**Issue by Ashish1998** [chimple/cuba#890]
Here the liked icon on lesson card is not properly displayed in the subjects screen.

![Screenshot_2023-09-11-17-06-51-99_ddc0fec0f25cadbb53407d57e5100bc9](https://github.com/chimple/cuba/assets/99384703/66888e27-6092-4b8f-a73b-5311a451e3ba)

**Comment by pratapramesh** [comment]
**The Liked icon is moving in all lesson card**

https://github.com/chimple/cuba/assets/138564361/b17b2e7b-5d9a-462a-a419-a18a946e8407
