### ISSUE TITLE
Below Grade 1 is showing in the subject screeen

### ISSUE THREAD

**Issue by Pramodmarssun** [chimple/cuba#895]
We are getting 3 grades in the chapter screen instead of Grade 1 and Grade 2

![Screenshot_20230912_123539_Chimple](https://github.com/chimple/cuba/assets/108517798/f2aa95ab-a151-4470-b3fc-d3eb2ccf72c9)

**Comment by Pramodmarssun** [comment]
Drop-Down grades are not in the order like Grade 1, and Grade 2

**Comment by SWETHAKRISHNA2** [comment]
It is working , Move to done

**Comment by Ashish1998** [comment]
We are getting "Below grade 1" in Digital skills.
![Screenshot_2023-09-20-11-15-58-09_ddc0fec0f25cadbb53407d57e5100bc9](https://github.com/chimple/cuba/assets/99384703/23628b41-8863-4b90-a7f9-4942f929f5e8)
