### ISSUE TITLE
Create Avatar Animation in rive

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#900]
Chimple avatar animation

- [ ] 1. Happy
- [ ] 2. Sad
- [x] 3. Talking
- [x] 4. Idle/blinking/moving head
- [ ] 5. Yay/congratulations
- [ ] 6. Sleepy/yawn
- [ ] 7. Funny/laughing
- [x] 8. Correct/yes
- [x] 9. Incorrect/no
- [ ] 10. Dance

**Comment by akshattak** [comment]
Chimple avatar animation
1. Happy
2. Sad
3. Talking
4. Idle/blinking/moving head
5. Yay/congratulations
6. Sleepy/yawn
7. Funny/laughing
8. Correct/yes
9. Incorrect/no
10. Dance
