### ISSUE TITLE
Glitch is appearing when we install the app first time 

### ISSUE THREAD

**Issue by Pramodmarssun** [chimple/cuba#903]
When we install the app the first time we can see the Login screen glitch 

https://github.com/chimple/cuba/assets/108517798/ec7a79db-0d3e-4a40-9615-6b69d027b85a

**Comment by Pramodmarssun** [comment]
This issue is still reproduceable in Lenovo tabs

**Log's of this issue**
[Glitch.txt](https://github.com/chimple/cuba/files/12735385/Glitch.txt)

**Comment by Ashish1998** [comment]
The glitch screen is not appearing now.
