### ISSUE TITLE
Homescreen enhancement for the avatar flow

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#916]

**Comment by Ashish1998** [comment]
**Issue:**
Here if we switch between Home screen and suggestion screen we are getting blank screen.

https://github.com/chimple/cuba/assets/99384703/61cc0e58-cb40-41d4-8f19-aa87183174cb

**Comment by Sutara-Skanda** [comment]
Here are the test cases for QA to perform:

- [ ] Grant QA access to the Avatar feature (Dev side).
- [ ] Monitor the time it takes to display the Avatar on a mobile device.
- [ ] After the Avatar appears on the screen, switch users back and forth to verify whether the Avatar disappears or not.
- [ ] After the Avatar appears on the screen, log out the user and log in again with the same credentials to check if the Avatar reappears.
- [ ] Repeat the 4th step with different user credentials that have access to the Avatar feature.
- [ ] Repeat the 4th step with different user credentials that do not have access to the Avatar feature.
