### ISSUE TITLE
Verify the translations in all languages  

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#921]

**Comment by faridarizwan** [comment]
https://docs.google.com/spreadsheets/d/1cigF3e1Svr5wCAnGD2xlPXW_eLiEP9nXLNHVHYggZx0/edit?usp=sharing
I have checked the above files. The issues which existed have been fixed. @bhanugummana , if you had any other issues which I have missed, please mark them in color or comment on them.
