### ISSUE TITLE
Issues in "Select parent language" (First screen)

### ISSUE THREAD

**Issue by Ashish1998** [chimple/cuba#935]
**These are the list of issues:**

- [x] When we change the language to Hindi still the texts in language selection screen be in English. If we select Kannada then texts will be in Hindi. Even if we go to sleep and return the selected option on the dropdown will be displayed as English.

https://github.com/chimple/cuba/assets/99384703/ec7ca308-816e-4d5a-8d64-38db1fa98f00

- [ ] When user selects Hindi and click on "next" button, the texts will still be displayed in English once if user clicks on phone number text field in login page then it will change to Hindi.

https://github.com/chimple/cuba/assets/99384703/5d4ce8ac-f4cb-4911-b7b2-c9b35a841e80

- [ ] Here when user selects language as Hindi in first screen and go to any profile and if he switch the profile the Language is changed to English. But if we check it in Parent screen it still shows the selected language as Hindi.

https://github.com/chimple/cuba/assets/99384703/b413d891-57dc-4843-bfff-64c89e076677

- [ ] Here after we sign-out and return to first screen, in drop down it shows the selected language as English but the other texts will be in the language which we selected before.

https://github.com/chimple/cuba/assets/99384703/a06a627e-52e7-4c09-a4ec-1c07489e1c6b

- [ ] The medium of instructions in the lessons are changing according to the "Parent language" but not to "Medium of instruction" 

https://github.com/chimple/cuba/assets/99384703/4fc9c0bb-6c25-4fcb-b952-33cf8a3d6d7e

**Comment by pratapramesh** [comment]
No issues
