### ISSUE TITLE
Issues in "Login screen".

### ISSUE THREAD

**Issue by Ashish1998** [chimple/cuba#939]
The issues are as follows,

- [ ] Here In the OTP screen the whole texts are scrollable. In the OTP screen the texts at the bottom is not fully visible in lenovo tabs. (This issue is present in the screen which contains text fields)
![Screenshot_2023-10-04-15-42-14-352](https://github.com/chimple/cuba/assets/99384703/e34834df-6e11-4ef2-a412-064947532345)

- [ ]  Here even after clicking on "resend OTP" button we are able login with the old OTP itself.

- [ ] Here in Lenovo tab still some of the alignment is not proper with the texts, For ex: The "continue with google" text overlaps with the lines. 
- [ ] "Send OTP" text on the button is not at the center.
![Screenshot_2023-10-04-15-46-38-385](https://github.com/chimple/cuba/assets/99384703/64dde643-f77a-4c5f-b323-757ca930ea3b)

**Comment by Pramodmarssun** [comment]
Log's 
[Phone auth.txt](https://github.com/chimple/cuba/files/13262566/Phone.auth.txt)
