### ISSUE TITLE
Issues in "create child's profile" flow 

### ISSUE THREAD

**Issue by Pramodmarssun** [chimple/cuba#940]
- [ ] We can see a padding above and bottom of the screen 

![Screenshot_2023-10-04-16-33-44-969_org chimple bahama](https://github.com/chimple/cuba/assets/108517798/5e4c7948-17c2-4d24-b15a-154c8bc91c6a)

- [x] If device goes to sleep in creating child's profile flow and once it's come back from the sleep, app will load and it will display the screen
- [x] In creating student profile flow and if device goes to sleep in **selecting gender, age or selecting avatar or Medium of instruction** once device come back from sleep we can see app will take us to **Enter child's name** screen

- [x] Here titles of the drop downs are not translated to Hindi and Kannada

https://github.com/chimple/cuba/assets/108517798/eab76693-f557-4e6f-89e2-77d8a130d1dd

**Comment by pratapramesh** [comment]
**We are not able to create a new profile**

**Comment by pratapramesh** [comment]
1. we are able to create more that 3 student profile 
![Screenshot_2023-11-06-16-27-39-109](https://github.com/chimple/cuba/assets/138564361/2e1d6950-7fa6-4448-9e2a-1b5905e29e57)

2. If i select gender as a girl and age is 8 go to sleep and come back means automatically it will select gender as boy and age is 5
3. If i select one avatar go to sleep and come back, automatically it will select different avatar
4. If device goes to sleep in creating child's profile flow and once it's come back from the sleep, app will load and it will display the screen issue still there

**Comment by pratapramesh** [comment]
No issues found
