### ISSUE TITLE
The Student data is mismatching in leader board

### ISSUE THREAD

**Issue by pratapramesh** [chimple/cuba#942]
**1. In this Student Profile the Student Data is mismatching like count of lesson played, Score and Time spent not same in Leader board
2. In this profile Remaining student Data also not displaying here**

![Screenshot_2023-10-04-17-11-45-513 (1)](https://github.com/chimple/cuba/assets/138564361/6c678b45-8d66-4c53-98a1-b3d2c2afb17a)

![Screenshot_2023-10-04-17-09-16-982 (1)](https://github.com/chimple/cuba/assets/138564361/d3ffadc9-5a6a-42ec-98e9-e084410c5ccb)

**Comment by divyahariharan2103** [comment]
Issue not reproducible
