### ISSUE TITLE
issue in profile/leader board

### ISSUE THREAD

**Issue by pratapramesh** [chimple/cuba#959]
- [ ] Alignment of the screen header is not proper "Switch profle button"

![Screenshot_2023-10-09-17-14-06-739](https://github.com/chimple/cuba/assets/138564361/b48286a2-1e9d-4b37-982d-dcd91321081c)

- [ ] Here we can see 'lesson played' not 'lessons played' & In the time spent we don't see a space between min and sec 

![Screenshot_2023-10-09-17-14-06-739](https://github.com/chimple/cuba/assets/138564361/593acb3f-34d3-43a0-a164-8896b66692c1)

- [ ] Student data will be not visible until he moved to atleast 50th level

![Screenshot_2023-10-09-17-20-55-593](https://github.com/chimple/cuba/assets/138564361/5530889b-15b9-41ca-9c6b-2cd54e8ad686)

**Comment by Pramodmarssun** [comment]
@Sutara-Skanda Not able to test. Here when we click on student profile we are getting blank screen in App and Web.

**Comment by SWETHAKRISHNA2** [comment]
space between min and sec  it is coming

![Screenshot_20240117_153321_Chimple](https://github.com/chimple/cuba/assets/138753773/7452ea74-190f-4213-b4fe-e3526b9cd09b)

![Screenshot_20240117_153422_Chimple](https://github.com/chimple/cuba/assets/138753773/25a6c305-ec50-4d71-90bc-f813a204553f)
