### ISSUE TITLE
Issues in Offline mode

### ISSUE THREAD

**Issue by Pramodmarssun** [chimple/cuba#964]
- [ ] We are not having any indication's to show Chimple app is in offline whenever app failed to connect to internet or very low internet 
- [ ] When we try to create new profile in offline mode we are not able to complete it due no internet and we are not showing any error message or indication that they can't create it 

https://github.com/chimple/cuba/assets/108517798/653b01e0-d8c0-456e-bdae-f434cb111596

**Comment by pratapramesh** [comment]
No issues
