### ISSUE TITLE
Support for download of lessons/chapters when parents have internet

### ISSUE THREAD

**Issue by talapadi** [chimple/cuba#983]

**Comment by talapadi** [comment]
- [ ] Check on startup with cache and update the local storage on the real status of the downloaded lessons
- [ ] No popup confirmation on click to download
- [ ] Popup confirmation on click to delete
- [ ] Snackbar on no internet when click to download
- [ ] Update the chapter status based on child lesson download/delete
- [ ] Update the lesson status to downloaded when child plays a lesson (because it is already downloaded)

**Comment by akshattak** [comment]
By tomorrow Alok will create the PR

**Comment by Ashish1998** [comment]
- [ ] UI issues in the suggestion screen, lessons screen and search screen, where the alignment of the lesson and chapter name, liked icon and stars icon.
![Screenshot_2023-12-11-15-19-21-85_ddc0fec0f25cadbb53407d57e5100bc9](https://github.com/chimple/cuba/assets/99384703/2425183d-bddc-46e9-9d2a-95af03663a02)
![Screenshot_2023-12-11-15-17-15-69_ddc0fec0f25cadbb53407d57e5100bc9](https://github.com/chimple/cuba/assets/99384703/353118ab-3970-4762-9eec-7f4ec77a87d8)
![Screenshot_2023-12-11-12-15-37-39_ddc0fec0f25cadbb53407d57e5100bc9](https://github.com/chimple/cuba/assets/99384703/f1b61e24-fdcc-4836-80f8-42375fb233a2)

- [ ] If we download 1 lesson in a profile, the same lesson is getting downloaded in the rest of the 2 profiles as well.
- [ ]  Once we download any lesson then while switching the screen in chapter screen we are getting a glitch.

- [ ] Alignment of the pop-up message which shows in offline is not proper in some devices.

![Screenshot_2023-12-11-12-38-57-253_org chimple bahama](https://github.com/chimple/cuba/assets/99384703/b8e02b05-5687-427d-9269-83f47c901f82)

- [ ] Delete button alignment not proper.

**Comment by Ashish1998** [comment]
- [ ] After playing a lesson we are not able to delete that lesson.

- [ ] If we switch between different screens we are getting a glitch in loading images of the lessons and chapters.

https://github.com/chimple/cuba/assets/99384703/9d6c7d59-911b-405a-9957-cff9cb0d7fbb

**Comment by Ashish1998** [comment]
- [ ] We download a chapter and then go to any other screens like suggestion screen or search screen and play any lesson and if we come back to chapter screen, even if the chapter is downloaded it still shows download icon.

https://github.com/chimple/cuba/assets/99384703/bf86998d-b721-4f5e-aab7-e01c7bf01df4

- [ ] The download button UI is not same in all the devices.

Lenovo tab:
![Screenshot_2023-12-20-12-13-28-528](https://github.com/chimple/cuba/assets/99384703/36e47208-117f-4343-9c82-0d9556a1e843)

Oneplus:
![Screenshot_2023-12-20-13-40-28-89_ddc0fec0f25cadbb53407d57e5100bc9](https://github.com/chimple/cuba/assets/99384703/d1cbc95b-e130-4608-82de-970c4c4b3353)

- [ ] Delete icon in delete button is not at the center.

![Screenshot_2023-12-20-13-32-57-025](https://github.com/chimple/cuba/assets/99384703/96daa11a-102b-43af-9598-1476c93b0343)

**Comment by pratapramesh** [comment]
Blank page will display when we Download and paly Quiz in offline


https://github.com/chimple/cuba/assets/138564361/8957eb94-f5eb-495d-bc6c-f7562b64ff88

**Comment by pratapramesh** [comment]
1. If we download any lesson card from some other page (suggestion, search, homework) and go to subject page there it is showing the compete chapter is downloaded, if you come back to chapter page there it will show download icon


https://github.com/chimple/cuba/assets/138564361/77afdb22-0a73-4ea5-8623-2e4bcf289cfb

2. In search page if we download any lessoncard from perticular chapter and search another lesson card from same chapter, that will also shows downloaded

https://github.com/chimple/cuba/assets/138564361/84f3511a-a538-476f-83ac-86c0f0a50e5d
