### ISSUE TITLE
Student data not displaying in Student "Progress report"

### ISSUE THREAD

**Issue by pratapramesh** [chimple/cuba#990]
**Steps to Reproduce**

1. Download the old bahama App from Playstore
2. Play lesson card from each subject
3. Update the App to Beta version
4. Click on Progress report in parent page

![Screenshot_20231018_150359](https://github.com/chimple/cuba/assets/138564361/acc1dca6-c4ba-4a83-9b5b-4afeeaaba946)

**Comment by divyahariharan2103** [comment]
Not reproducible
